# contractions_dict.py

contractions = {
    "'appen": "happen",
    "'cause": "because",
    "'ello": "hello",
    "'em": "them",
    "'til": "until",
    "'tis": "it is",
    "'twas": "it was",
    "'tweren't": "it were not",
    "'twill": "it will",
    "'twon't": "it will not",
    "'twould": "it would",
    "acct.": "account",
    "admin.": "administration",
    "afaik": "as far as I know",
    "ain't": "have not",
    "anybody's": "anybody is",
    "anyone's": "anyone is",
    "anything's": "anything is",
    "anywhere's": "anywhere is",
    "approx.": "approximately",
    "appt.": "appointment",
    "aren't": "are not",
    "assoc.": "association",
    "b/c": "because",
    "b/w": "between",
    "bc": "because",
    "brb": "be right back",
    "btw": "by the way",
    "c'mon": "come on",
    "can't": "cannot",
    "can't've": "cannot have",
    "cannae": "cannot",
    "cannot": "can not",
    "cat's": "cat has",
    "cat's paw": "catspaw",
    "cont'd": "continued",
    "corp.": "corporation",
    "could've": "could have",
    "couldn't": "could not",
    "couldn't've": "could not have",
    "cuz": "because",
    "d'ya": "do you",
    "d'ye": "do you",
    "d'you": "do you",
    "daren't": "dare not",
    "dept.": "department",
    "didnae": "did not",
    "dinnae": "do not",
    "doctor's": "doctor has",
    "doesn't": "does not",
    "dog's": "dog has",
    "don't": "do not",
    "dunno": "do not know",
    "e'er": "ever",
    "educ.": "education",
    "est'd": "established",
    "ev'ry": "every",
    "ev'ryone": "everyone",
    "ev'rything": "everything",
    "everybody's": "everybody is",
    "everyone's": "everyone is",
    "everything's": "everything is",
    "everywhere's": "everywhere is",
    "fo'c'sle": "forecastle",
    "friend's": "friend has",
    "g'afternoon": "good afternoon",
    "g'day": "good day",
    "g'evening": "good evening",
    "g'morning": "good morning",
    "g'night": "good night",
    "gimme": "give me",
    "gonna": "going to",
    "gotta": "got to",
    "gov't": "government",
    "gtg": "got to go",
    "hadn't": "had not",
    "hadnae": "had not",
    "hafta": "have to",
    "hasn't": "has not",
    "haven't": "have not",
    "havenae": "have not",
    "he'd": "he would",
    "he'd've": "he would have",
    "he'll": "he will",
    "he's": "he has",
    "how'd": "how did",
    "how'd've": "how would have",
    "how'll": "how will",
    "how're": "how are",
    "how's": "how is",
    "howdy": "how do you do",
    "i'd": "I would",
    "i'd've": "I would have",
    "i'll": "I will",
    "i'm": "I am",
    "i'm'a": "I am going to",
    "i'ma": "I am going to",
    "i've": "I have",
    "idk": "I do not know",
    "imho": "in my humble opinion",
    "imma": "I am going to",
    "imo": "in my opinion",
    "inc.": "incorporated",
    "innit": "is it not",
    "int'l": "international",
    "irl": "in real life",
    "isn't": "is not",
    "isnae": "is not",
    "it'd": "it would",
    "it'd've": "it would have",
    "it'll": "it will",
    "it's": "it has",
    "jack-o'-lantern": "jack of the lantern",
    "kinda": "kind of",
    "lemme": "let me",
    "let's": "let us",
    "lmao": "laughing my ass off",
    "lmk": "let me know",
    "lol'd": "laughed out loud",
    "ma'am": "madam",
    "man's": "man has",
    "may've": "may have",
    "mayn't": "may not",
    "might've": "might have",
    "mightn't": "might not",
    "mightn't've": "might not have",
    "misc.": "miscellaneous",
    "must've": "must have",
    "mustn't": "must not",
    "mustn't've": "must not have",
    "nat'l": "national",
    "ne'er": "never",
    "ne'er-do-well": "never do well",
    "needn't": "need not",
    "nobody's": "nobody is",
    "nothin'": "nothing",
    "nothing's": "nothing is",
    "nowhere's": "nowhere is",
    "nvm": "never mind",
    "o'clock": "of the clock",
    "o'er": "over",
    "ol'": "old",
    "omg": "oh my god",
    "omw": "on my way",
    "oughtn't": "ought not",
    "outta": "out of",
    "pls": "please",
    "rec'd": "received",
    "rn": "right now",
    "s'pose": "suppose",
    "s'posed": "supposed",
    "shan't": "shall not",
    "she'd": "she would",
    "she'd've": "she would have",
    "she'll": "she will",
    "she's": "she has",
    "should've": "should have",
    "shouldn't": "should not",
    "shouldn't've": "should not have",
    "somebody's": "somebody is",
    "someone's": "someone is",
    "somethin'": "something",
    "something's": "something is",
    "somewhere's": "somewhere is",
    "sorta": "sort of",
    "summat": "something",
    "summink": "something",
    "tbh": "to be honest",
    "temp.": "temporary",
    "that'd": "that would",
    "that's": "that is",
    "there'd": "there would",
    "there'd've": "there would have",
    "there'll": "there will",
    "there's": "there is",
    "there've": "there have",
    "they'd": "they would",
    "they'd've": "they would have",
    "they'll": "they will",
    "they're": "they are",
    "they've": "they have",
    "thx": "thanks",
    "univ.": "university",
    "w/": "with",
    "w/o": "without",
    "wanna": "want to",
    "wasn't": "was not",
    "wasnae": "was not",
    "we'd": "we would",
    "we'd've": "we would have",
    "we'll": "we will",
    "we're": "we are",
    "we've": "we have",
    "weren't": "were not",
    "what'd": "what did",
    "what'd've": "what would have",
    "what'll": "what will",
    "what's": "what is",
    "what've": "what have",
    "when'd": "when did",
    "when'd've": "when would have",
    "when'll": "when will",
    "when's": "when is",
    "where'd": "where did",
    "where'd've": "where would have",
    "where'll": "where will",
    "where's": "where is",
    "where've": "where have",
    "who'd": "who would",
    "who'd've": "who would have",
    "who'll": "who will",
    "who're": "who are",
    "who's": "who is",
    "who've": "who have",
    "why'd": "why did",
    "why'd've": "why would have",
    "why'll": "why will",
    "why's": "why is",
    "will-o'-the-wisp": "will of the wisp",
    "willnae": "will not",
    "woman's": "woman has",
    "won't": "will not",
    "won't've": "will not have",
    "would've": "would have",
    "wouldn't": "would not",
    "wouldn't've": "would not have",
    "wouldnae": "would not",
    "y'all": "you all",
    "y'all'd": "you all would",
    "y'all'd've": "you all would have",
    "y'all're": "you all are",
    "y'all've": "you all have",
    "you'd": "you would",
    "you'd've": "you would have",
    "you'll": "you will",
    "you're": "you are",
    "you've": "you have",
    "a.k.a.": "also known as",
    "abbrev.": "abbreviation",
    "adv.": "advertisement",
    "aft.": "afternoon",
    "alr": "alright",
    "am.": "ante meridiem",
    "apptd.": "appointed",
    "asap": "as soon as possible",
    "assn.": "association",
    "b-day": "birthday",
    "b4": "before",
    "bro": "brother",
    "c'ya": "see you",
    "cap'n": "captain",
    "cert.": "certificate",
    "co.": "company",
    "comm.": "communication",
    "congrats": "congratulations",
    "cos": "because",
    "cuzzie": "cousin",
    "d'yeh": "do you",
    "deffo": "definitely",
    "diff.": "difference",
    "div.": "division",
    "diy": "do it yourself",
    "doc.": "document",
    "doncha": "do not you",
    "dontcha": "do not you",
    "e.g.": "for example",
    "econ.": "economics",
    "esp.": "especially",
    "etc.": "et cetera",
    "ev'rybody": "everybody",
    "ev'rywhere": "everywhere",
    "exec.": "executive",
    "fam": "family",
    "fav": "favorite",
    "fig.": "figure",
    "finna": "fixing to",
    "freq.": "frequently",
    "frnd.": "friend",
    "fwd": "forward",
    "gal.": "gallon",
    "gen.": "general",
    "gen'l": "general",
    "giv'n": "given",
    "goin'": "going",
    "gon'": "going",
    "gotcha": "got you",
    "h'd": "had",
    "h'lo": "hello",
    "h'okay": "okay",
    "h'w": "how",
    "hasn't've": "has not have",
    "he'ya": "here you are",
    "hey'd": "hey would",
    "hi'd": "hi would",
    "hiya": "hello",
    "hld.": "hold",
    "hrs": "hours",
    "i.e.": "that is",
    "info.": "information",
    "init.": "initial",
    "intl.": "international",
    "is't": "is it",
    "it'sa": "it is a",
    "j/k": "just kidding",
    "jr.": "junior",
    "kthx": "okay thanks",
    "lab.": "laboratory",
    "lit.": "literally",
    "luv": "love",
    "m'kay": "okay",
    "max.": "maximum",
    "med.": "medium",
    "mgr.": "manager",
    "min.": "minimum",
    "miscel.": "miscellaneous",
    "mkay": "okay",
    "msg.": "message",
    "n/a": "not applicable",
    "n/e": "no entry",
    "n/m": "never mind",
    "n/t": "not",
    "n/t've": "not have",
    "n/th": "nth",
    "n'the": "in the",
    "n'their": "not their",
    "n'this": "not this",
    "n/thing": "nothing",
    "n/though": "not though",
    "n'time": "no time",
    "n'to": "not to",
    "n'twas": "not was",
    "n'twere": "not were",
    "n/where": "nowhere",
    "naw": "no",
    "nxt": "next",
    "ofc": "of course",
    "org.": "organization",
    "orig.": "original",
    "p.m.": "post meridiem",
    "perf.": "performance",
    "pls'd": "pleased",
    "pop.": "population",
    "prob.": "probably",
    "prof.": "professor",
    "qty.": "quantity",
    "re.": "regarding",
    "rep.": "representative",
    "req.": "required",
    "res.": "reservation",
    "rly": "really",
    "rm.": "room",
    "rofl": "rolling on the floor laughing",
    "sec.": "second",
    "sis": "sister",
    "sitch": "situation",
    "smh": "shaking my head",
    "snooze": "sleep",
    "spec.": "special",
    "sr.": "senior",
    "std.": "standard",
    "sup": "what's up",
    "sux": "sucks",
    "t'other": "the other",
    "t'was": "it was",
    "ta": "thanks",
    "tech.": "technology",
    "temp'": "temporary",
    "th'": "the",
    "thanx": "thanks",
    "tho'": "though",
    "thru": "through",
    "til": "until",
    "tmrw": "tomorrow",
    "tryna": "trying to",
    "ttyl": "talk to you later",
    "twas'": "it was",
    "tween'": "between",
    "txt": "text",
    "u'd": "you would",
    "u'll": "you will",
    "u're": "you are",
    "u've": "you have",
    "ur": "your",
    "v.": "versus",
    "vid.": "video",
    "vol.": "volume",
    "w/ever": "whatever",
    "w/o'ever": "without ever",
    "wassup": "what's up",
    "whatevs": "whatever",
    "whatcha": "what are you",
    "whate'er": "whatever",
    "whatnot": "what not",
    "whatsit": "what is it",
    "whene'er": "whenever",
    "where'er": "wherever",
    "whiche'er": "whichever",
    "whoe'er": "whoever",
    "whyd'ya": "why do you",
    "wk.": "week",
    "wkd.": "weekend",
    "wld.": "would",
    "wldn't": "would not",
    "wld've": "would have",
    "wtf": "what the fuck",
    "wth": "what the hell",
    "wuz": "was",
    "wuzup": "what's up",
    "y'd": "you had",
    "y'd've": "you would have",
    "y'know": "you know",
    "y'see": "you see",
    "ya": "you",
    "ye'd": "you would",
    "ye'll": "you will",
    "ye're": "you are",
    "ye've": "you have",
    "yer": "your",
    "yerself": "yourself",
    "yessir": "yes sir",
    "yup": "yes",
    "yrs.": "years",
    "yrs'elf": "yourself",
    "yrs'elves": "yourselves",
    "zup": "what's up"
}