filler_words = {
    "well", "um", "uh", "hmm", "like", "you know", "actually", "maybe",
    "sort of", "kind of", "okay", "huh", "anyway", "I mean",
    "alright", "perhaps", "you see", "honestly", "basically",
    "guess", "somehow", "though", "really?", "oh", "huh?", "eh",
    "so", "right", "totally", "literally", "y'know", "I guess",
    "whatever", "stuff like that", "or something", "you know what I mean",
    "at the end of the day", "to be honest", "er", "ah", "yep", "kinda",
    "sorta", "yup", "sure", "I dunno", "basically speaking", "in a way",
    "as it were", "you get me", "I suppose", "pretty much", "you know how it is",
    "and stuff", "or whatever", "like I said", "to tell you the truth", "in other words",
    "by the way", "just saying", "no kidding", "come on", "let's see",
    "hang on", "hold on", "you got it", "I get it", "fair enough",
    "so to speak", "as a matter of fact", "to be fair", "not gonna lie",
    "all right then", "what else", "you know what", "in any case",
    "at any rate", "on the other hand", "to put it simply", "more or less",
    "if you will", "I reckon", "you could say", "like I was saying",
    "anyhow", "to be real", "what can I say", "I hear you", "no doubt",
    "for real", "in a sense", "and all that", "you feel me", "I'm like",
    "to be frank", "look", "see", "c'mon", "right?", "well then",
    "as if", "gotcha", "uh-huh", "yeppers", "I'd say", "let me think",
    "and whatnot", "like whatever", "you know the drill", "in a bit",
    "to be clear", "you know what I'm saying", "or so", "just so you know",
    "mind you", "all that jazz", "so yeah", "I hear ya", "no lie",
    "for sure", "like you know", "at this point", "in the end",
    "to sum up", "you catch my drift", "basically like", "or like",
    "to be precise", "you get what I mean", "and so on", "like that",
    "hold up", "you with me", "I see", "no way", "uhm", "erm",
    "like really", "in fact", "to be sure", "what's that", "you know right",
    "just like", "as you know", "I'm saying", "on second thought",
    "to be blunt", "you dig", "in short", "kinda like", "you know how",
    "that's about it", "or what", "like so", "to tell the truth",
    "whatnot", "you got me", "I mean like", "so basically", "check it",
    "to put it another way", "like yeah", "you hear me", "in all honesty",
    "just you know", "for what it's worth", "to make it quick", "you following",
    "like no joke", "at least", "you know the deal", "to be exact",
    "I'm telling you", "sort of like", "you know what's up", "in any event",
    "like c'mon", "to cut a long story short", "you see what I mean",
    "anyways", "like honestly", "you know what I'm getting at", "in a nutshell",
    "you got that", "to be straight", "like for real", "just to clarify",
    "you know the thing is", "in case you're wondering", "like duh",
    "to be realistic", "you know it", "at the same time", "like I mean",
    "to wrap it up", "you know what's what", "in all fairness", "like sure",
    "you get the idea", "to be completely honest", "like whoa", "you know the score",
    "mmm", "ehm", "ahem", "hmmm", "um-um", "uh-uh", "er-er", "ah-ah",
    "mm-hmm", "uhm-hm", "erm-erm", "huh-huh", "ooh", "ahh", "ugh",
    "ehh", "ohh", "mhm", "hm", "umh", "uhm-uhm", "eh-eh", "oh-oh",
    "mm", "ah-uh", "um-mm", "huh-um", "er-uh", "uh-hm",
    "you know what I'm talking about", "like totally", "you know what's good",
    "to keep it short", "like you get it", "you know the vibe", "just to say",
    "like I'm saying", "you know how it goes", "to put it that way",
    "you know what's what", "like come on now", "you know the gist",
    "to break it down", "like no way", "you know the lowdown",
    "just to put it out there", "you know what I'm about", "like for sure",
    "to keep it simple", "you know the routine", "like I get you",
    "you know what's the deal", "just to be real", "like you know it",
    "to make it plain", "you know the story", "like let's be real",
    "you know how we do", "just to break it down", "like you feel me",
    "to keep it one hundred", "you know what's real", "like no cap",
    "you know the play", "just to keep it real", "like you know how",
    "to put it out there", "you know what's good with it", "like straight up",
    "you know the move", "just to make it clear", "like you know what's up",
    "to lay it out", "you know what I'm driving at", "like you know the score",
    "you tracking", "you hear", "you with it", "you cool", "you good",
    "you see me", "you picking up", "you catching on", "you following me",
    "you on board", "you get the drift", "you in", "you vibing",
    "you tuned in", "you locked in", "you on the same page", "you down",
    "you reading me", "you picking this up", "you catching my vibe",
    "you on the wavelength", "you getting this", "you in sync",
    "you feeling this", "you keeping up", "you on track", "you with the program",
    "you seeing this", "you catching the drift", "you in the loop",
    "you getting the picture", "you on the same vibe", "you following along",
    "you in the know", "you getting my point", "you on my level",
    "you catching what I'm throwing", "you with the vibe", "you hearing this",
    "you picking up what I'm putting down",
    "moving on", "anywho", "back to it", "so anyway", "next up",
    "let's move on", "on that note", "to switch gears", "let's keep it moving",
    "anyhow now", "back to the point", "so like", "to change it up",
    "let's get to it", "onward", "to shift gears", "let's roll on",
    "so moving forward", "to get back to it", "anyways then",
    "let's pivot", "to bring it back", "so what's next", "to wrap things up",
    "let's get on with it", "to move along", "so let's go", "to keep going",
    "let's jump back in", "so next", "to pick it back up", "let's carry on",
    "so to continue", "to get back on track", "let's push forward",
    "so where was I", "to circle back", "let's dive back in",
    "so let's keep going", "to jump to it", "let's get back",
    "yo", "like legit", "for realz", "no cap", "straight up", "bet",
    "like facts", "deadass", "no shade", "like fr", "real talk",
    "like no lie", "100", "keep it 100", "like deadass", "no tea",
    "like straight up", "facts", "like bet", "no bs", "like real talk",
    "straight facts", "like no cap", "keep it real", "like 100",
    "no frontin'", "like facts only", "straight no chaser", "like no bs",
    "real shit", "like keep it 100", "no cap fr", "like straight facts",
    "deadass fr", "like no shade", "straight talk", "like no tea",
    "facts only", "like real shit", "no cap no lie", "like keep it real",
    "mate", "innit", "cheers", "ta", "oi", "bloke", "lad", "matey",
    "guv", "luv", "alright mate", "you alright", "cheers then",
    "ta muchly", "oi mate", "right then", "you good mate", "innit though",
    "like mate", "cheers mate", "ta for that", "oi you", "right mate",
    "you alright then", "innit like", "mate you know", "cheers for that",
    "ta like", "oi c'mon", "right you are", "you good then", "innit right",
    "mate like", "cheers now", "ta then", "oi right", "you alright mate",
    "prithee", "forsooth", "verily", "methinks", "perchance", "mayhap",
    "in sooth", "to wit", "haply", "belike", "forasmuche", "withal",
    "in truth", "peradventure", "an't", "t'other", "in sooth verily",
    "prithee now", "forsooth then", "verily so", "methinks perhaps",
    "perchance maybe", "mayhap so", "in truth now", "to wit then",
    "haply so", "belike maybe", "forasmuche as", "withal then",
    "in sooth like", "peradventure now",
    "tbh", "imo", "fyi", "brb", "btw", "irl", "smh", "lmao", "rofl",
    "af", "lit", "yolo", "savage", "on fleek", "poppin'", "turnt",
    "like omg", "for real tho", "no cap tho", "like lmao", "straight up tho",
    "bet af", "like tbh", "imo like", "fyi tho", "brb like", "btw tho",
    "irl like", "smh tho", "lmao like", "rofl tho", "af like", "lit tho",
    "yolo like", "savage tho", "on fleek tho", "poppin' like", "turnt tho"
}

# Single-word filler words
single_word_fillers = {
    "well", "um", "uh", "hmm", "like", "actually", "maybe", "okay", 
    "huh", "anyway", "alright", "perhaps", "honestly", "basically",
    "guess", "somehow", "though", "really?", "oh", "huh?", "eh",
    "so", "right", "totally", "literally", "whatever", "er", "ah", 
    "yep", "kinda", "sorta", "yup", "sure", "anyways", "look", "see", 
    "c'mon", "right?", "gotcha", "uh-huh", "yeppers", "whatnot", 
    "uhm", "erm", "mmm", "ehm", "ahem", "hmmm", "ooh", "ahh", "ugh",
    "ehh", "ohh", "mhm", "hm", "umh", "mm", "yo", "bet", "deadass", 
    "facts", "100", "mate", "innit", "cheers", "ta", "oi", "bloke", 
    "lad", "matey", "guv", "luv", "prithee", "forsooth", "verily", 
    "methinks", "perchance", "mayhap", "haply", "belike", "withal",
    "an't", "t'other", "tbh", "imo", "fyi", "brb", "btw", "irl", 
    "smh", "lmao", "rofl", "af", "lit", "yolo", "savage", "turnt",
    "onward", "anyhow"
}

# Multi-word/phrase filler words
phrase_fillers = {
    "you know", "sort of", "kind of", "I mean", "you see", "I guess",
    "stuff like that", "or something", "you know what I mean",
    "at the end of the day", "to be honest", "I dunno", "basically speaking", 
    "in a way", "as it were", "you get me", "I suppose", "pretty much", 
    "you know how it is", "and stuff", "or whatever", "like I said", 
    "to tell you the truth", "in other words", "by the way", "just saying", 
    "no kidding", "come on", "let's see", "hang on", "hold on", "you got it", 
    "I get it", "fair enough", "so to speak", "as a matter of fact", 
    "to be fair", "not gonna lie", "all right then", "what else", 
    "you know what", "in any case", "at any rate", "on the other hand", 
    "to put it simply", "more or less", "if you will", "I reckon", 
    "you could say", "like I was saying", "to be real", "what can I say", 
    "I hear you", "no doubt", "for real", "in a sense", "and all that", 
    "you feel me", "I'm like", "to be frank", "well then", "as if", 
    "let me think", "and whatnot", "like whatever", "you know the drill", 
    "in a bit", "to be clear", "you know what I'm saying", "or so", 
    "just so you know", "mind you", "all that jazz", "so yeah", "I hear ya", 
    "no lie", "for sure", "like you know", "at this point", "in the end",
    "to sum up", "you catch my drift", "basically like", "or like",
    "to be precise", "you get what I mean", "and so on", "like that",
    "hold up", "you with me", "I see", "no way", "like really", 
    "in fact", "to be sure", "what's that", "you know right",
    "just like", "as you know", "I'm saying", "on second thought",
    "to be blunt", "you dig", "in short", "kinda like", "you know how",
    "that's about it", "or what", "like so", "to tell the truth",
    "you got me", "I mean like", "so basically", "check it",
    "to put it another way", "like yeah", "you hear me", "in all honesty",
    "just you know", "for what it's worth", "to make it quick", "you following",
    "like no joke", "at least", "you know the deal", "to be exact",
    "I'm telling you", "sort of like", "you know what's up", "in any event",
    "like c'mon", "to cut a long story short", "you see what I mean",
    "like honestly", "you know what I'm getting at", "in a nutshell",
    "you got that", "to be straight", "like for real", "just to clarify",
    "you know the thing is", "in case you're wondering", "like duh",
    "to be realistic", "you know it", "at the same time", "like I mean",
    "to wrap it up", "you know what's what", "in all fairness", "like sure",
    "you get the idea", "to be completely honest", "like whoa", "you know the score",
    "um-um", "uh-uh", "er-er", "ah-ah", "mm-hmm", "uhm-hm", "erm-erm", 
    "huh-huh", "uhm-uhm", "eh-eh", "oh-oh", "ah-uh", "um-mm", "huh-um", 
    "er-uh", "uh-hm", "you know what I'm talking about", "like totally", 
    "you know what's good", "to keep it short", "like you get it", 
    "you know the vibe", "just to say", "like I'm saying", "you know how it goes", 
    "to put it that way", "you know what's what", "like come on now", 
    "you know the gist", "to break it down", "like no way", 
    "you know the lowdown", "just to put it out there", "you know what I'm about", 
    "like for sure", "to keep it simple", "you know the routine", "like I get you",
    "you know what's the deal", "just to be real", "like you know it",
    "to make it plain", "you know the story", "like let's be real",
    "you know how we do", "just to break it down", "like you feel me",
    "to keep it one hundred", "you know what's real", "like no cap",
    "you know the play", "just to keep it real", "like you know how",
    "to put it out there", "you know what's good with it", "like straight up",
    "you know the move", "just to make it clear", "like you know what's up",
    "to lay it out", "you know what I'm driving at", "like you know the score",
    "you tracking", "you hear", "you with it", "you cool", "you good",
    "you see me", "you picking up", "you catching on", "you following me",
    "you on board", "you get the drift", "you in", "you vibing",
    "you tuned in", "you locked in", "you on the same page", "you down",
    "you reading me", "you picking this up", "you catching my vibe",
    "you on the wavelength", "you getting this", "you in sync",
    "you feeling this", "you keeping up", "you on track", "you with the program",
    "you seeing this", "you catching the drift", "you in the loop",
    "you getting the picture", "you on the same vibe", "you following along",
    "you in the know", "you getting my point", "you on my level",
    "you catching what I'm throwing", "you with the vibe", "you hearing this",
    "you picking up what I'm putting down", "moving on", "anywho", "back to it", 
    "so anyway", "next up", "let's move on", "on that note", "to switch gears", 
    "let's keep it moving", "anyhow now", "back to the point", "so like", 
    "to change it up", "let's get to it", "to shift gears", "let's roll on",
    "so moving forward", "to get back to it", "anyways then",
    "let's pivot", "to bring it back", "so what's next", "to wrap things up",
    "let's get on with it", "to move along", "so let's go", "to keep going",
    "let's jump back in", "so next", "to pick it back up", "let's carry on",
    "so to continue", "to get back on track", "let's push forward",
    "so where was I", "to circle back", "let's dive back in",
    "so let's keep going", "to jump to it", "let's get back",
    "like legit", "for realz", "no cap", "straight up", 
    "like facts", "no shade", "like fr", "real talk",
    "like no lie", "keep it 100", "like deadass", "no tea",
    "like straight up", "like bet", "no bs", "like real talk",
    "straight facts", "like no cap", "keep it real", "like 100",
    "no frontin'", "like facts only", "straight no chaser", "like no bs",
    "real shit", "like keep it 100", "no cap fr", "like straight facts",
    "deadass fr", "like no shade", "straight talk", "like no tea",
    "facts only", "like real shit", "no cap no lie", "like keep it real",
    "alright mate", "you alright", "cheers then",
    "ta muchly", "oi mate", "right then", "you good mate", "innit though",
    "like mate", "cheers mate", "ta for that", "oi you", "right mate",
    "you alright then", "innit like", "mate you know", "cheers for that",
    "ta like", "oi c'mon", "right you are", "you good then", "innit right",
    "mate like", "cheers now", "ta then", "oi right", "you alright mate",
    "in sooth", "to wit", "in truth", "peradventure", "in sooth verily",
    "prithee now", "forsooth then", "verily so", "methinks perhaps",
    "perchance maybe", "mayhap so", "in truth now", "to wit then",
    "haply so", "belike maybe", "forasmuche as", "withal then",
    "in sooth like", "peradventure now",
    "like omg", "for real tho", "no cap tho", "like lmao", "straight up tho",
    "bet af", "like tbh", "imo like", "fyi tho", "brb like", "btw tho",
    "irl like", "smh tho", "lmao like", "rofl tho", "af like", "lit tho",
    "yolo like", "savage tho", "on fleek tho", "poppin' like", "turnt tho"
}

phrase_emotion_dict = {
    'you know': {'label': 0, 'tags': 'affirmation, emphasis, colloquial, transition, sarcasm', 'emotion_tags': 'supportive, positive'},
    'sort of': {'label': 0, 'tags': 'colloquial, transition, emphasis, hesitation, sarcasm, filler', 'emotion_tags': 'confused, neutral'},
    'kind of': {'label': 1, 'tags': 'colloquial, emphasis, transition, hesitation, sarcasm, affirmation', 'emotion_tags': 'confused, supportive, neutral'},
    'I mean': {'label': 0, 'tags': 'emphasis, affirmation, colloquial, transition', 'emotion_tags': 'positive, supportive'},
    'you see': {'label': 0, 'tags': 'affirmation, emphasis, colloquial, transition', 'emotion_tags': 'positive, supportive'},
    'I guess': {'label': 0, 'tags': 'colloquial, emphasis, hesitation, transition, affirmation, sarcasm', 'emotion_tags': 'confused, neutral, supportive'},
    'stuff like that': {'label': 0, 'tags': 'emphasis', 'emotion_tags': 'casual,relaxed'},
    'or something': {'label': 0, 'tags': 'emphasis, colloquial, transition, hesitation, affirmation', 'emotion_tags': 'confused'},
    'you know what I mean': {'label': 0, 'tags': 'affirmation, colloquial, emphasis, transition, sarcasm', 'emotion_tags': 'supportive'},
    'at the end of the day': {'label': 0, 'tags': 'affirmation', 'emotion_tags': 'supportive, confused'},
    'to be honest': {'label': 1, 'tags': 'emphasis, transition, hesitation, colloquial', 'emotion_tags': 'confused, negative, neutral'},
    'I dunno': {'label': 0, 'tags': 'hesitation, colloquial, sarcasm, emphasis, transition', 'emotion_tags': 'confused, neutral, sarcastic, negative'},
    'basically speaking': {'label': 0, 'tags': 'colloquial, transition', 'emotion_tags': 'supportive'},
    'in a way': {'label': 0, 'tags': 'colloquial, emphasis, transition, affirmation, sarcasm, hesitation', 'emotion_tags': 'positive, supportive, confused'},
    'as it were': {'label': 0, 'tags': 'colloquial, emphasis, affirmation, transition, sarcasm', 'emotion_tags': 'positive, supportive, sarcastic'},
    'you get me': {'label': 0, 'tags': 'affirmation, emphasis, colloquial, transition, hesitation, sarcasm', 'emotion_tags': 'supportive, positive'},
    'I suppose': {'label': 0, 'tags': 'emphasis, colloquial, transition, affirmation, hesitation', 'emotion_tags': 'confused, supportive, neutral'},
    'pretty much': {'label': 1, 'tags': 'emphasis, colloquial, affirmation, transition', 'emotion_tags': 'positive, supportive, neutral'},
    'you know how it is': {'label': 0, 'tags': 'colloquial, affirmation, emphasis, transition, sarcasm', 'emotion_tags': 'negative'},
    'and stuff': {'label': 0, 'tags': 'emphasis, transition, colloquial', 'emotion_tags': 'confused, supportive'},
    'or whatever': {'label': 0, 'tags': 'emphasis, colloquial, transition', 'emotion_tags': 'confused'},
    'like I said': {'label': 0, 'tags': 'emphasis, affirmation, colloquial, transition, sarcasm', 'emotion_tags': 'supportive, positive'},
    'to tell you the truth': {'label': 0, 'tags': 'emphasis, affirmation', 'emotion_tags': 'honesty,sincerity'},
    'in other words': {'label': 0, 'tags': 'colloquial, emphasis, transition, affirmation', 'emotion_tags': 'confused, supportive'},
    'by the way': {'label': 0, 'tags': 'emphasis, affirmation, transition, colloquial, sarcasm', 'emotion_tags': 'confused, supportive'},
    'just saying': {'label': 0, 'tags': 'colloquial, emphasis, sarcasm, filler, hesitation, transition, affirmation', 'emotion_tags': 'sarcastic, confused, negative, neutral'},
    'no kidding': {'label': 0, 'tags': 'emphasis, sarcasm, affirmation, transition', 'emotion_tags': 'negative, confused, sarcastic'},
    'come on': {'label': 0, 'tags': 'emphasis, transition, hesitation, colloquial, affirmation', 'emotion_tags': 'confused, negative'},
    "let's see": {'label': 0, 'tags': 'emphasis, colloquial, affirmation, transition', 'emotion_tags': 'confused, supportive'},
    'hang on': {'label': 0, 'tags': 'emphasis, affirmation, transition, hesitation, colloquial, sarcasm, filler', 'emotion_tags': 'supportive, confused, sarcastic, positive'},
    'hold on': {'label': 0, 'tags': 'emphasis, hesitation, transition, colloquial, affirmation, sarcasm', 'emotion_tags': 'confused'},
    'you got it': {'label': 0, 'tags': 'affirmation, emphasis, transition, colloquial', 'emotion_tags': 'positive, supportive'},
    'I get it': {'label': 0, 'tags': 'affirmation, emphasis, transition, colloquial, hesitation', 'emotion_tags': 'supportive, positive'},
    'fair enough': {'label': 1, 'tags': 'affirmation, emphasis, transition, colloquial', 'emotion_tags': 'supportive, positive, neutral'},
    'so to speak': {'label': 0, 'tags': 'colloquial, emphasis, affirmation, transition, sarcasm', 'emotion_tags': 'supportive, positive, confused'},
    'as a matter of fact': {'label': 0, 'tags': 'emphasis, affirmation', 'emotion_tags': 'positive, supportive'},
    'to be fair': {'label': 1, 'tags': 'emphasis, affirmation, colloquial', 'emotion_tags': 'positive, supportive'},
    'not gonna lie': {'label': 0, 'tags': 'emphasis, sarcasm, hesitation, transition, affirmation, colloquial', 'emotion_tags': 'negative, confused, sarcastic'},
    'all right then': {'label': 0, 'tags': 'affirmation, emphasis, transition, colloquial', 'emotion_tags': 'supportive, positive'},
    'what else': {'label': 0, 'tags': 'emphasis, colloquial', 'emotion_tags': 'confused'},
    'you know what': {'label': 0, 'tags': 'affirmation, colloquial, emphasis, sarcasm, transition', 'emotion_tags': 'supportive, positive, neutral, sarcastic'},
    'in any case': {'label': 0, 'tags': 'emphasis, affirmation, transition, colloquial', 'emotion_tags': 'positive, supportive, confused'},
    'at any rate': {'label': 0, 'tags': 'emphasis, transition, affirmation, colloquial', 'emotion_tags': 'confused, supportive, positive'},
    'on the other hand': {'label': 0, 'tags': 'transition, emphasis, colloquial, hesitation, affirmation', 'emotion_tags': 'confused, supportive'},
    'to put it simply': {'label': 0, 'tags': 'colloquial, emphasis, transition, affirmation', 'emotion_tags': 'negative, supportive, positive, neutral'},
    'more or less': {'label': 0, 'tags': 'colloquial, transition, emphasis, affirmation', 'emotion_tags': 'confused'},
    'if you will': {'label': 0, 'tags': 'affirmation, colloquial, emphasis, transition, hesitation, sarcasm', 'emotion_tags': 'supportive, confused, positive'},
    'I reckon': {'label': 0, 'tags': 'affirmation, emphasis, colloquial, transition, hesitation, sarcasm', 'emotion_tags': 'confused, positive, supportive'},
    'you could say': {'label': 0, 'tags': 'colloquial, emphasis, affirmation, transition', 'emotion_tags': 'supportive, positive'},
    'like I was saying': {'label': 0, 'tags': 'emphasis, affirmation, colloquial, transition, sarcasm', 'emotion_tags': 'supportive, positive, confused'},
    'to be real': {'label': 0, 'tags': 'emphasis, affirmation, transition', 'emotion_tags': 'positive, supportive'},
    'what can I say': {'label': 0, 'tags': 'filler, colloquial, hesitation, transition', 'emotion_tags': 'confused, neutral'},
    'I hear you': {'label': 0, 'tags': 'affirmation, emphasis, colloquial, transition, hesitation', 'emotion_tags': 'supportive, positive'},
    'no doubt': {'label': 1, 'tags': 'affirmation, emphasis, transition', 'emotion_tags': 'positive, supportive, negative'},
    'for real': {'label': 0, 'tags': 'affirmation, emphasis, transition', 'emotion_tags': 'positive, supportive'},
    'in a sense': {'label': 0, 'tags': 'emphasis, colloquial, affirmation, transition, hesitation', 'emotion_tags': 'confused, supportive, positive'},
    'and all that': {'label': 0, 'tags': 'emphasis, affirmation', 'emotion_tags': 'positive, supportive, confused'},
    'you feel me': {'label': 0, 'tags': 'affirmation, emphasis, hesitation, transition, colloquial, sarcasm', 'emotion_tags': 'supportive, confused, negative, sarcastic'},
    "I'm like": {'label': 0, 'tags': 'affirmation, emphasis, colloquial, hesitation, transition, sarcasm', 'emotion_tags': 'confused, supportive, neutral, positive, sarcastic'},
    'to be frank': {'label': 0, 'tags': 'emphasis, transition, colloquial', 'emotion_tags': 'negative, confused'},
    'well then': {'label': 0, 'tags': 'affirmation, emphasis, transition, colloquial, sarcasm', 'emotion_tags': 'positive, supportive, confused, sarcastic'},
    'as if': {'label': 0, 'tags': 'colloquial, emphasis, sarcasm, affirmation, hesitation, transition', 'emotion_tags': 'confused, sarcastic, supportive, positive'},
    'let me think': {'label': 0, 'tags': 'hesitation, emphasis, colloquial, transition', 'emotion_tags': 'confused, supportive'},
    'and whatnot': {'label': 0, 'tags': 'emphasis, colloquial, transition', 'emotion_tags': 'confused'},
    'like whatever': {'label': 0, 'tags': 'colloquial, affirmation, emphasis, transition, sarcasm, filler', 'emotion_tags': 'confused, supportive, neutral, positive, sarcastic'},
    'you know the drill': {'label': 0, 'tags': 'transition, affirmation, colloquial', 'emotion_tags': 'confidence,familiarity,casual'},
    'in a bit': {'label': 0, 'tags': 'transition, emphasis, colloquial, hesitation, affirmation', 'emotion_tags': 'confused, supportive'},
    'to be clear': {'label': 1, 'tags': 'emphasis, affirmation, transition', 'emotion_tags': 'positive, supportive'},
    "you know what I'm saying": {'label': 0, 'tags': 'affirmation, emphasis, colloquial, transition, sarcasm', 'emotion_tags': 'supportive'},
    'or so': {'label': 0, 'tags': 'emphasis, colloquial, affirmation, transition, hesitation', 'emotion_tags': 'confused, supportive'},
    'just so you know': {'label': 0, 'tags': 'emphasis, affirmation, sarcasm, transition, colloquial, hesitation', 'emotion_tags': 'negative, confused'},
    'mind you': {'label': 0, 'tags': 'emphasis, colloquial, affirmation, sarcasm, hesitation, transition', 'emotion_tags': 'confused, negative, sarcastic'},
    'all that jazz': {'label': 0, 'tags': 'emphasis, affirmation', 'emotion_tags': 'positive, supportive'},
    'so yeah': {'label': 0, 'tags': 'affirmation, emphasis, colloquial, transition, sarcasm', 'emotion_tags': 'positive, supportive, confused, sarcastic'},
    'I hear ya': {'label': 0, 'tags': 'affirmation, emphasis, colloquial, transition, hesitation, sarcasm', 'emotion_tags': 'supportive, positive, confused'},
    'no lie': {'label': 0, 'tags': 'affirmation, emphasis, transition', 'emotion_tags': 'positive, supportive'},
    'for sure': {'label': 1, 'tags': 'affirmation, emphasis, transition', 'emotion_tags': 'positive, supportive'},
    'like you know': {'label': 0, 'tags': 'affirmation, emphasis, colloquial, sarcasm, transition', 'emotion_tags': 'supportive, positive, sarcastic'},
    'at this point': {'label': 0, 'tags': 'emphasis, affirmation, transition, colloquial, hesitation', 'emotion_tags': 'confused, supportive, positive'},
    'in the end': {'label': 0, 'tags': 'emphasis, affirmation, transition, colloquial', 'emotion_tags': 'supportive, positive'},
    'to sum up': {'label': 0, 'tags': 'emphasis, affirmation, colloquial', 'emotion_tags': 'positive, supportive'},
    'you catch my drift': {'label': 0, 'tags': 'emphasis, colloquial, affirmation, transition, sarcasm, hesitation', 'emotion_tags': 'supportive, confused'},
    'basically like': {'label': 0, 'tags': 'colloquial, emphasis, affirmation, transition', 'emotion_tags': 'supportive, positive, neutral'},
    'or like': {'label': 0, 'tags': 'emphasis, affirmation, colloquial, transition', 'emotion_tags': 'positive, supportive, confused'},
    'to be precise': {'label': 1, 'tags': 'emphasis, affirmation, transition', 'emotion_tags': 'positive, supportive'},
    'you get what I mean': {'label': 0, 'tags': 'affirmation, emphasis, colloquial, transition', 'emotion_tags': 'supportive'},
    'and so on': {'label': 0, 'tags': 'emphasis, colloquial, transition, affirmation', 'emotion_tags': 'confused, supportive'},
    'like that': {'label': 0, 'tags': 'emphasis, affirmation, colloquial, transition, sarcasm', 'emotion_tags': 'positive, supportive, confused'},
    'hold up': {'label': 0, 'tags': 'emphasis, affirmation, colloquial, transition', 'emotion_tags': 'supportive, confused, positive'},
    'you with me': {'label': 0, 'tags': 'affirmation, emphasis, colloquial, transition, hesitation', 'emotion_tags': 'supportive, positive, confused'},
    'I see': {'label': 0, 'tags': 'affirmation, emphasis, transition, colloquial', 'emotion_tags': 'positive, supportive'},
    'no way': {'label': 0, 'tags': 'emphasis, hesitation, transition, sarcasm', 'emotion_tags': 'negative, confused, sarcastic'},
    'like really': {'label': 1, 'tags': 'affirmation, emphasis, colloquial, transition', 'emotion_tags': 'positive, supportive, confused'},
    'in fact': {'label': 0, 'tags': 'affirmation, emphasis, transition', 'emotion_tags': 'positive, supportive'},
    'to be sure': {'label': 1, 'tags': 'affirmation, emphasis, transition', 'emotion_tags': 'positive, supportive'},
    "what's that": {'label': 0, 'tags': 'colloquial, emphasis, hesitation', 'emotion_tags': 'confused'},
    'you know right': {'label': 0, 'tags': 'affirmation, emphasis, colloquial, transition', 'emotion_tags': 'supportive, positive'},
    'just like': {'label': 0, 'tags': 'affirmation, emphasis, colloquial, transition', 'emotion_tags': 'positive, supportive, neutral'},
    'as you know': {'label': 0, 'tags': 'affirmation, emphasis, transition', 'emotion_tags': 'supportive, positive'},
    "I'm saying": {'label': 0, 'tags': 'emphasis, affirmation, colloquial, transition, sarcasm', 'emotion_tags': 'supportive, positive'},
    'on second thought': {'label': 0, 'tags': 'hesitation, transition, emphasis, colloquial', 'emotion_tags': 'confused'},
    'to be blunt': {'label': 0, 'tags': 'emphasis, colloquial, transition', 'emotion_tags': 'negative, confused'},
    'you dig': {'label': 0, 'tags': 'affirmation, emphasis, transition, colloquial', 'emotion_tags': 'positive, supportive'},
    'in short': {'label': 0, 'tags': 'filler, colloquial, emphasis, transition, hesitation, affirmation', 'emotion_tags': 'negative, confused, supportive, positive'},
    'kinda like': {'label': 0, 'tags': 'colloquial, emphasis, affirmation, transition, hesitation', 'emotion_tags': 'supportive, confused, positive, neutral'},
    'you know how': {'label': 0, 'tags': 'affirmation, emphasis, colloquial, transition', 'emotion_tags': 'supportive'},
    "that's about it": {'label': 0, 'tags': 'filler, colloquial', 'emotion_tags': 'neutral'},
    'or what': {'label': 0, 'tags': 'emphasis, colloquial, transition, hesitation', 'emotion_tags': 'confused'},
    'like so': {'label': 0, 'tags': 'affirmation, emphasis, colloquial, transition, sarcasm', 'emotion_tags': 'supportive, positive'},
    'to tell the truth': {'label': 0, 'tags': 'emphasis, affirmation', 'emotion_tags': 'honesty,sincerity'},
    'you got me': {'label': 0, 'tags': 'affirmation, emphasis, sarcasm, transition, colloquial, hesitation', 'emotion_tags': 'supportive, positive, sarcastic, negative'},
    'I mean like': {'label': 0, 'tags': 'affirmation, colloquial, emphasis', 'emotion_tags': 'positive, supportive, confused, neutral'},
    'so basically': {'label': 0, 'tags': 'colloquial, affirmation, emphasis, transition', 'emotion_tags': 'supportive, positive'},
    'check it': {'label': 0, 'tags': 'emphasis, affirmation, transition, colloquial', 'emotion_tags': 'supportive, positive'},
    'to put it another way': {'label': 0, 'tags': 'colloquial, emphasis, transition, affirmation, sarcasm, hesitation', 'emotion_tags': 'confused, supportive'},
    'like yeah': {'label': 1, 'tags': 'affirmation, emphasis, colloquial, transition, sarcasm, hesitation', 'emotion_tags': 'positive, supportive, confused, sarcastic'},
    'you hear me': {'label': 0, 'tags': 'emphasis, affirmation, colloquial, transition, sarcasm', 'emotion_tags': 'supportive, positive'},
    'in all honesty': {'label': 1, 'tags': 'emphasis, affirmation, transition', 'emotion_tags': 'positive, neutral, supportive, confused'},
    'just you know': {'label': 0, 'tags': 'affirmation, emphasis, colloquial, filler, sarcasm, transition, hesitation', 'emotion_tags': 'supportive, sarcastic, neutral, negative'},
    "for what it's worth": {'label': 1, 'tags': 'emphasis, affirmation, transition, sarcasm', 'emotion_tags': 'supportive, positive, confused'},
    'to make it quick': {'label': 0, 'tags': 'transition, colloquial, filler, emphasis, affirmation', 'emotion_tags': 'positive'},
    'you following': {'label': 0, 'tags': 'affirmation, emphasis, transition, colloquial', 'emotion_tags': 'supportive, positive'},
    'like no joke': {'label': 0, 'tags': 'emphasis, affirmation', 'emotion_tags': 'confused, negative'},
    'at least': {'label': 0, 'tags': 'emphasis, affirmation, transition', 'emotion_tags': 'positive, supportive'},
    'you know the deal': {'label': 0, 'tags': 'affirmation, emphasis, colloquial, transition', 'emotion_tags': 'supportive'},
    'to be exact': {'label': 0, 'tags': 'emphasis, affirmation, transition', 'emotion_tags': 'positive, supportive'},
    "I'm telling you": {'label': 0, 'tags': 'emphasis, affirmation, colloquial, transition', 'emotion_tags': 'supportive, positive'},
    'sort of like': {'label': 0, 'tags': 'colloquial, emphasis, affirmation, transition', 'emotion_tags': 'confused, supportive, neutral, positive'},
    "you know what's up": {'label': 0, 'tags': 'affirmation, emphasis, colloquial, transition, sarcasm', 'emotion_tags': 'supportive'},
    'in any event': {'label': 0, 'tags': 'emphasis, affirmation, transition', 'emotion_tags': 'positive, supportive, confused'},
    "like c'mon": {'label': 0, 'tags': 'colloquial, emphasis, hesitation, sarcasm, affirmation, transition', 'emotion_tags': 'confused, negative, sarcastic'},
    'to cut a long story short': {'label': 0, 'tags': 'filler, transition', 'emotion_tags': 'confused, negative'},
    'you see what I mean': {'label': 0, 'tags': 'emphasis, affirmation, transition, colloquial, sarcasm', 'emotion_tags': 'supportive, positive'},
    'like honestly': {'label': 1, 'tags': 'emphasis, affirmation, colloquial, transition', 'emotion_tags': 'supportive, positive, neutral'},
    "you know what I'm getting at": {'label': 0, 'tags': 'emphasis, affirmation, transition, colloquial, sarcasm', 'emotion_tags': 'supportive'},
    'in a nutshell': {'label': 0, 'tags': 'emphasis, affirmation, transition', 'emotion_tags': 'positive, supportive'},
    'you got that': {'label': 0, 'tags': 'affirmation, emphasis, colloquial, transition', 'emotion_tags': 'positive, supportive'},
    'to be straight': {'label': 1, 'tags': 'emphasis, affirmation', 'emotion_tags': 'positive, supportive'},
    'like for real': {'label': 1, 'tags': 'emphasis, affirmation, transition', 'emotion_tags': 'positive, supportive'},
    'just to clarify': {'label': 0, 'tags': 'emphasis, transition, colloquial, hesitation', 'emotion_tags': 'confused'},
    'you know the thing is': {'label': 0, 'tags': 'affirmation, emphasis, colloquial', 'emotion_tags': 'supportive'},
    "in case you're wondering": {'label': 0, 'tags': 'emphasis, transition, colloquial', 'emotion_tags': 'confused'},
    'like duh': {'label': 0, 'tags': 'affirmation, emphasis, colloquial, transition', 'emotion_tags': 'supportive, positive'},
    'to be realistic': {'label': 0, 'tags': 'emphasis, transition', 'emotion_tags': 'supportive'},
    'you know it': {'label': 0, 'tags': 'affirmation, emphasis, colloquial, sarcasm, transition', 'emotion_tags': 'supportive, positive'},
    'at the same time': {'label': 0, 'tags': 'emphasis, affirmation, transition', 'emotion_tags': 'supportive'},
    'like I mean': {'label': 0, 'tags': 'colloquial, emphasis, affirmation, transition', 'emotion_tags': 'supportive, positive'},
    'to wrap it up': {'label': 0, 'tags': 'emphasis, affirmation, colloquial, transition', 'emotion_tags': 'supportive, positive'},
    "you know what's what": {'label': 0, 'tags': 'affirmation, emphasis, colloquial', 'emotion_tags': 'supportive'},
    'in all fairness': {'label': 0, 'tags': 'emphasis, affirmation, transition', 'emotion_tags': 'supportive, positive, neutral'},
    'like sure': {'label': 1, 'tags': 'affirmation, emphasis, colloquial, transition, sarcasm', 'emotion_tags': 'positive, supportive'},
    'you get the idea': {'label': 0, 'tags': 'emphasis, affirmation, transition, colloquial', 'emotion_tags': 'supportive'},
    'to be completely honest': {'label': 1, 'tags': 'emphasis, transition', 'emotion_tags': 'confused, negative'},
    'like whoa': {'label': 0, 'tags': 'emphasis, affirmation, colloquial, transition', 'emotion_tags': 'confused, positive'},
    'you know the score': {'label': 0, 'tags': 'affirmation', 'emotion_tags': 'confidence'},
    'um-um': {'label': 0, 'tags': 'emphasis, colloquial, sarcasm, transition, affirmation, hesitation', 'emotion_tags': 'confused, negative, sarcastic, supportive, positive'},
    'uh-uh': {'label': 0, 'tags': 'colloquial, emphasis, hesitation, transition, sarcasm, affirmation', 'emotion_tags': 'confused, negative, sarcastic, supportive'},
    'er-er': {'label': 0, 'tags': 'emphasis, colloquial, affirmation, transition, sarcasm, hesitation', 'emotion_tags': 'confused, supportive, positive, sarcastic'},
    'ah-ah': {'label': 0, 'tags': 'colloquial, emphasis, affirmation, sarcasm, transition, hesitation', 'emotion_tags': 'confused, sarcastic, supportive, positive'},
    'mm-hmm': {'label': 0, 'tags': 'affirmation, emphasis, colloquial, hesitation, sarcasm, transition', 'emotion_tags': 'confused, supportive, sarcastic, positive'},
    'uhm-hm': {'label': 0, 'tags': 'colloquial, emphasis, hesitation, affirmation, transition, sarcasm', 'emotion_tags': 'confused, sarcastic, supportive, positive'},
    'erm-erm': {'label': 0, 'tags': 'colloquial, emphasis, sarcasm, affirmation, transition, hesitation, filler', 'emotion_tags': 'confused, sarcastic, supportive, negative, positive'},
    'huh-huh': {'label': 0, 'tags': 'affirmation, emphasis, colloquial, sarcasm, transition, hesitation', 'emotion_tags': 'confused, sarcastic, supportive, positive'},
    'uhm-uhm': {'label': 0, 'tags': 'colloquial, emphasis, hesitation, affirmation, transition, sarcasm', 'emotion_tags': 'confused, supportive, sarcastic, positive, negative'},
    'eh-eh': {'label': 0, 'tags': 'colloquial, emphasis, sarcasm, hesitation, transition, affirmation', 'emotion_tags': 'negative, confused, sarcastic, supportive, positive'},
    'oh-oh': {'label': 0, 'tags': 'colloquial, hesitation, emphasis, sarcasm, transition', 'emotion_tags': 'confused, negative, sarcastic'},
    'ah-uh': {'label': 0, 'tags': 'colloquial, emphasis, hesitation, sarcasm, transition, affirmation', 'emotion_tags': 'confused, sarcastic, negative, supportive, positive'},
    'um-mm': {'label': 0, 'tags': 'emphasis, colloquial, sarcasm, transition, hesitation, affirmation', 'emotion_tags': 'confused, sarcastic, negative, supportive, positive'},
    'huh-um': {'label': 0, 'tags': 'colloquial, emphasis, sarcasm, hesitation, affirmation, transition', 'emotion_tags': 'confused, sarcastic, supportive, positive'},
    'er-uh': {'label': 0, 'tags': 'colloquial, emphasis, hesitation, transition, sarcasm, affirmation', 'emotion_tags': 'confused, negative, sarcastic, supportive, positive'},
    'uh-hm': {'label': 0, 'tags': 'emphasis, colloquial, hesitation, affirmation, transition, sarcasm', 'emotion_tags': 'confused, sarcastic, supportive, positive'},
    "you know what I'm talking about": {'label': 0, 'tags': 'emphasis, affirmation, colloquial, hesitation, transition', 'emotion_tags': 'supportive'},
    'like totally': {'label': 0, 'tags': 'emphasis, affirmation, transition, colloquial', 'emotion_tags': 'supportive, positive'},
    "you know what's good": {'label': 1, 'tags': 'affirmation, emphasis, colloquial, transition', 'emotion_tags': 'positive, supportive'},
    'to keep it short': {'label': 0, 'tags': 'filler, colloquial, transition, emphasis', 'emotion_tags': 'neutral, supportive, negative'},
    'like you get it': {'label': 0, 'tags': 'affirmation, emphasis, colloquial, transition', 'emotion_tags': 'supportive, positive'},
    'you know the vibe': {'label': 0, 'tags': 'colloquial, affirmation, emphasis, transition, hesitation', 'emotion_tags': 'supportive, positive'},
    'just to say': {'label': 0, 'tags': 'filler, colloquial, emphasis, affirmation, sarcasm, transition', 'emotion_tags': 'sarcastic, confused'},
    "like I'm saying": {'label': 0, 'tags': 'emphasis, colloquial, affirmation, transition, sarcasm', 'emotion_tags': 'supportive, positive, confused'},
    'you know how it goes': {'label': 0, 'tags': 'colloquial, transition, affirmation', 'emotion_tags': 'understanding,familiarity,casual'},
    'to put it that way': {'label': 0, 'tags': 'emphasis, colloquial, affirmation, sarcasm, transition, hesitation', 'emotion_tags': 'positive, negative, sarcastic, supportive'},
    'like come on now': {'label': 0, 'tags': 'emphasis, transition, affirmation, hesitation, colloquial', 'emotion_tags': 'confused, negative'},
    'you know the gist': {'label': 0, 'tags': 'emphasis, affirmation, colloquial', 'emotion_tags': 'familiarity,understanding,casual'},
    'to break it down': {'label': 0, 'tags': 'transition, colloquial, emphasis', 'emotion_tags': 'helpfulness,clarity,patience'},
    'like no way': {'label': 0, 'tags': 'emphasis, hesitation, sarcasm, transition', 'emotion_tags': 'negative, confused, sarcastic'},
    'you know the lowdown': {'label': 0, 'tags': 'colloquial', 'emotion_tags': 'negative'},
    'just to put it out there': {'label': 0, 'tags': 'emphasis, sarcasm, filler, affirmation, colloquial, transition', 'emotion_tags': 'sarcastic, negative, confused'},
    "you know what I'm about": {'label': 0, 'tags': 'affirmation, emphasis, colloquial, transition', 'emotion_tags': 'supportive, positive'},
    'like for sure': {'label': 1, 'tags': 'affirmation, emphasis, colloquial, transition', 'emotion_tags': 'positive, supportive'},
    'to keep it simple': {'label': 0, 'tags': 'colloquial, transition', 'emotion_tags': 'neutral, supportive, positive'},
    'you know the routine': {'label': 0, 'tags': 'affirmation, colloquial, transition', 'emotion_tags': 'supportive,familiarity'},
    'like I get you': {'label': 0, 'tags': 'affirmation, emphasis, colloquial, transition', 'emotion_tags': 'supportive, positive'},
    "you know what's the deal": {'label': 0, 'tags': 'affirmation, emphasis, transition', 'emotion_tags': 'familiarity,confidence,casual'},
    'just to be real': {'label': 0, 'tags': 'emphasis, filler, colloquial, hesitation, sarcasm, transition, affirmation', 'emotion_tags': 'negative, confused'},
    'like you know it': {'label': 0, 'tags': 'affirmation, emphasis, colloquial, sarcasm', 'emotion_tags': 'supportive, positive'},
    'to make it plain': {'label': 0, 'tags': 'emphasis, affirmation, transition', 'emotion_tags': 'supportive, negative, positive'},
    'you know the story': {'label': 0, 'tags': 'affirmation', 'emotion_tags': 'familiarity,understanding,casual'},
    "like let's be real": {'label': 1, 'tags': 'emphasis, hesitation, transition, colloquial, affirmation', 'emotion_tags': 'confused, negative, neutral'},
    'you know how we do': {'label': 0, 'tags': 'affirmation, colloquial, emphasis, transition', 'emotion_tags': 'supportive'},
    'just to break it down': {'label': 0, 'tags': 'transition, colloquial', 'emotion_tags': 'helpfulness,clarity,patience'},
    'like you feel me': {'label': 0, 'tags': 'affirmation, emphasis, colloquial, transition, hesitation', 'emotion_tags': 'supportive, positive'},
    'to keep it one hundred': {'label': 0, 'tags': 'emphasis, affirmation', 'emotion_tags': 'supportive, positive'},
    "you know what's real": {'label': 0, 'tags': 'affirmation, emphasis', 'emotion_tags': 'supportive, positive'},
    'like no cap': {'label': 0, 'tags': 'emphasis, colloquial, affirmation, sarcasm, filler, hesitation', 'emotion_tags': 'negative, confused, neutral, supportive, positive, sarcastic'},
    'you know the play': {'label': 0, 'tags': 'affirmation, colloquial', 'emotion_tags': 'familiarity,confidence'},
    'just to keep it real': {'label': 0, 'tags': 'emphasis, hesitation', 'emotion_tags': 'negative'},
    'like you know how': {'label': 0, 'tags': 'affirmation, emphasis, colloquial, transition', 'emotion_tags': 'supportive, positive'},
    'to put it out there': {'label': 0, 'tags': 'emphasis, affirmation, sarcasm, transition, colloquial', 'emotion_tags': 'supportive'},
    "you know what's good with it": {'label': 1, 'tags': 'affirmation, emphasis, colloquial, transition', 'emotion_tags': 'positive, supportive, neutral'},
    'like straight up': {'label': 1, 'tags': 'emphasis, affirmation', 'emotion_tags': 'positive, supportive'},
    'you know the move': {'label': 0, 'tags': 'transition, affirmation, colloquial, emphasis', 'emotion_tags': 'supportive'},
    'just to make it clear': {'label': 1, 'tags': 'emphasis, affirmation, transition', 'emotion_tags': 'confidence, clarity' },
    "like you know what's up": {'label': 0, 'tags': 'affirmation, emphasis, colloquial, transition', 'emotion_tags': 'supportive'},
    'to lay it out': {'label': 0, 'tags': 'emphasis, transition, colloquial, affirmation', 'emotion_tags': 'supportive'},
    "you know what I'm driving at": {'label': 0, 'tags': 'emphasis, affirmation, colloquial, sarcasm, transition', 'emotion_tags': 'sarcastic'},
    'like you know the score': {'label': 0, 'tags': 'affirmation, emphasis, colloquial', 'emotion_tags': 'supportive'},
    'you tracking': {'label': 0, 'tags': 'emphasis', 'emotion_tags': 'alertness, urgency'},
    'you hear': {'label': 0, 'tags': 'emphasis, affirmation, colloquial, transition, hesitation, sarcasm', 'emotion_tags': 'supportive, confused, positive, negative'},
    'you with it': {'label': 0, 'tags': 'emphasis, affirmation, colloquial, transition', 'emotion_tags': 'supportive, positive'},
    'you cool': {'label': 1, 'tags': 'affirmation, emphasis, transition, colloquial, sarcasm', 'emotion_tags': 'positive, supportive'},
    'you good': {'label': 1, 'tags': 'affirmation, emphasis, transition, colloquial', 'emotion_tags': 'positive, supportive'},
    'you see me': {'label': 0, 'tags': 'affirmation, emphasis, transition, colloquial, sarcasm', 'emotion_tags': 'supportive, positive, confused'},
    'you picking up': {'label': 0, 'tags': 'emphasis, transition, affirmation, colloquial', 'emotion_tags': 'supportive, positive'},
    'you catching on': {'label': 1, 'tags': 'affirmation, emphasis, transition, colloquial', 'emotion_tags': 'positive, supportive'},
    'you following me': {'label': 0, 'tags': 'affirmation, emphasis, transition, colloquial', 'emotion_tags': 'supportive, confused, positive'},
    'you on board': {'label': 0, 'tags': 'affirmation, emphasis, transition, colloquial', 'emotion_tags': 'supportive, positive'},
    'you get the drift': {'label': 0, 'tags': 'affirmation, colloquial, transition, emphasis', 'emotion_tags': 'supportive'},
    'you in': {'label': 0, 'tags': 'affirmation, emphasis, transition, colloquial', 'emotion_tags': 'supportive, positive, confused'},
    'you vibing': {'label': 0, 'tags': 'affirmation, emphasis, colloquial, transition', 'emotion_tags': 'positive, supportive'},
    'you tuned in': {'label': 0, 'tags': 'emphasis, affirmation, transition, colloquial', 'emotion_tags': 'supportive, positive'},
    'you locked in': {'label': 0, 'tags': 'emphasis, affirmation', 'emotion_tags': 'negative'},
    'you on the same page': {'label': 0, 'tags': 'affirmation, emphasis, transition', 'emotion_tags': 'supportive, positive'},
    'you down': {'label': 0, 'tags': 'sarcasm, colloquial, hesitation', 'emotion_tags': 'negative, confused, sarcastic'},
    'you reading me': {'label': 0, 'tags': 'emphasis, affirmation, transition, colloquial, hesitation', 'emotion_tags': 'confused, supportive'},
    'you picking this up': {'label': 0, 'tags': 'emphasis, affirmation, transition, colloquial', 'emotion_tags': 'supportive, positive'},
    'you catching my vibe': {'label': 1, 'tags': 'affirmation, emphasis, transition, hesitation, colloquial', 'emotion_tags': 'supportive, positive, confused'},
    'you on the wavelength': {'label': 0, 'tags': 'colloquial, affirmation, emphasis, transition', 'emotion_tags': 'supportive, positive, sarcastic, neutral'},
    'you getting this': {'label': 0, 'tags': 'affirmation, emphasis, transition, colloquial', 'emotion_tags': 'supportive, positive'},
    'you in sync': {'label': 0, 'tags': 'affirmation, emphasis', 'emotion_tags': 'supportive, positive'},
    'you feeling this': {'label': 0, 'tags': 'affirmation, emphasis, colloquial, transition, hesitation', 'emotion_tags': 'supportive, positive, confused'},
    'you keeping up': {'label': 0, 'tags': 'affirmation, emphasis, transition', 'emotion_tags': 'supportive, positive'},
    'you on track': {'label': 0, 'tags': 'affirmation, emphasis', 'emotion_tags': 'positive, supportive'},
    'you with the program': {'label': 0, 'tags': 'emphasis, affirmation, transition', 'emotion_tags': 'supportive, positive'},
    'you seeing this': {'label': 0, 'tags': 'emphasis, affirmation, transition, colloquial', 'emotion_tags': 'supportive, positive'},
    'you catching the drift': {'label': 1, 'tags': 'affirmation, colloquial, emphasis, transition', 'emotion_tags': 'supportive'},
    'you in the loop': {'label': 0, 'tags': 'emphasis, affirmation, transition', 'emotion_tags': 'supportive, positive'},
    'you getting the picture': {'label': 0, 'tags': 'emphasis, affirmation, transition', 'emotion_tags': 'supportive'},
    'you on the same vibe': {'label': 0, 'tags': 'affirmation, emphasis, colloquial', 'emotion_tags': 'supportive, positive, neutral'},
    'you following along': {'label': 0, 'tags': 'affirmation, transition, emphasis, colloquial', 'emotion_tags': 'supportive, positive'},
    'you in the know': {'label': 0, 'tags': 'affirmation, emphasis, transition', 'emotion_tags': 'supportive'},
    'you getting my point': {'label': 0, 'tags': 'emphasis, affirmation, transition', 'emotion_tags': 'supportive'},
    'you on my level': {'label': 0, 'tags': 'affirmation, emphasis, colloquial, transition', 'emotion_tags': 'supportive, positive'},
    "you catching what I'm throwing": {'label': 1, 'tags': 'affirmation, emphasis, transition', 'emotion_tags': 'supportive, confused, positive'},
    'you with the vibe': {'label': 0, 'tags': 'affirmation, emphasis, colloquial, transition', 'emotion_tags': 'supportive, positive'},
    'you hearing this': {'label': 0, 'tags': 'emphasis, affirmation, colloquial, transition, sarcasm, hesitation', 'emotion_tags': 'supportive, confused, positive, negative'},
    "you picking up what I'm putting down": {'label': 0, 'tags': 'emphasis, transition, affirmation, colloquial, sarcasm', 'emotion_tags': 'supportive, confused'},
    'moving on': {'label': 0, 'tags': 'transition, emphasis, affirmation, colloquial', 'emotion_tags': 'positive, supportive'},
    'anywho': {'label': 0, 'tags': 'colloquial, emphasis, transition, sarcasm, affirmation, hesitation', 'emotion_tags': 'confused, sarcastic, supportive'},
    'back to it': {'label': 0, 'tags': 'transition, emphasis, affirmation, hesitation, colloquial', 'emotion_tags': 'confused, supportive'},
    'so anyway': {'label': 0, 'tags': 'emphasis, colloquial, affirmation, transition, sarcasm, hesitation', 'emotion_tags': 'confused, supportive, positive, sarcastic'},
    'next up': {'label': 0, 'tags': 'transition, emphasis, affirmation', 'emotion_tags': 'supportive'},
    "let's move on": {'label': 0, 'tags': 'transition, affirmation, emphasis, colloquial', 'emotion_tags': 'confused, positive'},
    'on that note': {'label': 0, 'tags': 'emphasis, affirmation, transition, colloquial, sarcasm, hesitation', 'emotion_tags': 'positive, supportive, negative'},
    'to switch gears': {'label': 0, 'tags': 'transition, colloquial, emphasis', 'emotion_tags': 'positive'},
    "let's keep it moving": {'label': 0, 'tags': 'transition, emphasis, affirmation, colloquial', 'emotion_tags': 'positive, supportive, confused'},
    'anyhow now': {'label': 0, 'tags': 'emphasis, transition, affirmation, colloquial', 'emotion_tags': 'confused, supportive, positive'},
    'back to the point': {'label': 0, 'tags': 'emphasis, transition, colloquial', 'emotion_tags': 'focus, clarity'},
    'so like': {'label': 1, 'tags': 'affirmation, emphasis, colloquial, transition', 'emotion_tags': 'positive, supportive'},
    'to change it up': {'label': 0, 'tags': 'transition, emphasis, colloquial', 'emotion_tags': 'confused, positive'},
    "let's get to it": {'label': 0, 'tags': 'emphasis, transition, affirmation, colloquial', 'emotion_tags': 'supportive, positive'},
    'to shift gears': {'label': 0, 'tags': 'transition, emphasis, colloquial', 'emotion_tags': 'change, alertness'},
    "let's roll on": {'label': 0, 'tags': 'transition, affirmation, emphasis, colloquial', 'emotion_tags': 'positive, supportive, confused'},
    'so moving forward': {'label': 0, 'tags': 'transition, emphasis, affirmation, colloquial', 'emotion_tags': 'positive, supportive'},
    'to get back to it': {'label': 0, 'tags': 'emphasis, transition, hesitation, affirmation, colloquial', 'emotion_tags': 'confused, supportive'},
    'anyways then': {'label': 0, 'tags': 'emphasis, transition, affirmation, colloquial', 'emotion_tags': 'confused, supportive, positive'},
    "let's pivot": {'label': 0, 'tags': 'transition, emphasis, colloquial, hesitation, affirmation', 'emotion_tags': 'confused, supportive, positive'},
    'to bring it back': {'label': 0, 'tags': 'emphasis, affirmation, hesitation, colloquial', 'emotion_tags': 'supportive, confused, positive'},
    "so what's next": {'label': 0, 'tags': 'transition, colloquial, emphasis', 'emotion_tags': 'confused'},
    'to wrap things up': {'label': 0, 'tags': 'emphasis, affirmation, transition, colloquial', 'emotion_tags': 'supportive, positive'},
    "let's get on with it": {'label': 0, 'tags': 'emphasis, transition, affirmation, colloquial', 'emotion_tags': 'supportive, positive, confused'},
    'to move along': {'label': 0, 'tags': 'transition, emphasis, affirmation, colloquial', 'emotion_tags': 'positive, supportive'},
    "so let's go": {'label': 0, 'tags': 'affirmation, emphasis, transition, colloquial', 'emotion_tags': 'supportive, positive, confused'},
    'to keep going': {'label': 0, 'tags': 'affirmation, emphasis, transition, colloquial', 'emotion_tags': 'supportive, positive'},
    "let's jump back in": {'label': 0, 'tags': 'transition, emphasis, affirmation, hesitation, colloquial', 'emotion_tags': 'supportive, confused'},
    'so next': {'label': 0, 'tags': 'transition, emphasis, affirmation, colloquial, sarcasm', 'emotion_tags': 'confused, supportive, positive, sarcastic'},
    'to pick it back up': {'label': 0, 'tags': 'transition, emphasis, affirmation, hesitation, colloquial', 'emotion_tags': 'confused, supportive'},
    "let's carry on": {'label': 0, 'tags': 'affirmation, emphasis, transition, colloquial', 'emotion_tags': 'supportive, positive'},
    'so to continue': {'label': 0, 'tags': 'emphasis, affirmation, transition, colloquial', 'emotion_tags': 'supportive, positive, confused'},
    'to get back on track': {'label': 0, 'tags': 'transition, emphasis, affirmation, hesitation', 'emotion_tags': 'confused, positive, supportive'},
    "let's push forward": {'label': 0, 'tags': 'emphasis, affirmation, transition, colloquial', 'emotion_tags': 'positive, supportive'},
    'so where was I': {'label': 0, 'tags': 'emphasis, colloquial, transition, hesitation', 'emotion_tags': 'confused'},
    'to circle back': {'label': 0, 'tags': 'hesitation, emphasis, affirmation, transition, colloquial', 'emotion_tags': 'supportive, confused, positive'},
    "let's dive back in": {'label': 0, 'tags': 'transition, emphasis, affirmation, hesitation', 'emotion_tags': 'supportive, confused'},
    "so let's keep going": {'label': 0, 'tags': 'affirmation, emphasis, transition, colloquial', 'emotion_tags': 'supportive, positive, confused'},
    'to jump to it': {'label': 0, 'tags': 'transition, emphasis, affirmation, colloquial', 'emotion_tags': 'urgency, readiness'},
    "let's get back": {'label': 0, 'tags': 'emphasis, transition, affirmation, hesitation, colloquial', 'emotion_tags': 'confused, supportive, positive'},
    'like legit': {'label': 0, 'tags': 'affirmation, emphasis, transition, colloquial', 'emotion_tags': 'positive, supportive, neutral'},
    'for realz': {'label': 0, 'tags': 'emphasis, affirmation, transition', 'emotion_tags': 'positive, supportive'},
    'no cap': {'label': 0, 'tags': 'emphasis, hesitation, colloquial, filler, transition, affirmation, sarcasm', 'emotion_tags': 'negative, confused, neutral, positive, supportive'},
    'straight up': {'label': 1, 'tags': 'emphasis, affirmation', 'emotion_tags': 'positive'},
    'like facts': {'label': 0, 'tags': 'affirmation, emphasis', 'emotion_tags': 'supportive, positive'},
    'no shade': {'label': 0, 'tags': 'transition, affirmation, emphasis', 'emotion_tags': 'negative, neutral, positive, confused'},
    'like fr': {'label': 0, 'tags': 'emphasis, affirmation, colloquial, transition, hesitation, sarcasm', 'emotion_tags': 'supportive, positive, confused'},
    'real talk': {'label': 0, 'tags': 'emphasis, affirmation, colloquial', 'emotion_tags': 'negative, positive'},
    'like no lie': {'label': 0, 'tags': 'affirmation, emphasis, colloquial', 'emotion_tags': 'positive, supportive'},
    'keep it 100': {'label': 0, 'tags': 'affirmation, emphasis, colloquial', 'emotion_tags': 'positive, supportive'},
    'like deadass': {'label': 0, 'tags': 'sarcasm, emphasis, colloquial', 'emotion_tags': 'negative, sarcastic, confused'},
    'no tea': {'label': 0, 'tags': 'emphasis, hesitation, colloquial, transition, sarcasm, filler', 'emotion_tags': 'negative, confused, neutral, sarcastic'},
    'like bet': {'label': 0, 'tags': 'emphasis, colloquial, affirmation', 'emotion_tags': 'supportive, positive, confused'},
    'no bs': {'label': 0, 'tags': 'sarcasm, colloquial, hesitation, filler, emphasis, transition', 'emotion_tags': 'negative, confused, sarcastic, neutral'},
    'like real talk': {'label': 1, 'tags': 'emphasis, affirmation, colloquial', 'emotion_tags': 'supportive, positive'},
    'straight facts': {'label': 1, 'tags': 'emphasis, affirmation, colloquial', 'emotion_tags': 'confidence, clarity'},
    'keep it real': {'label': 0, 'tags': 'emphasis, colloquial', 'emotion_tags': 'negative'},
    'like 100': {'label': 0, 'tags': 'emphasis, affirmation, transition, colloquial', 'emotion_tags': 'supportive, positive, confused'},
    "no frontin'": {'label': 0, 'tags': 'affirmation, colloquial, emphasis, transition', 'emotion_tags': 'negative, neutral, supportive, positive, confused'},
    'like facts only': {'label': 0, 'tags': 'emphasis, affirmation, colloquial', 'emotion_tags': 'clarity, assertiveness'},
    'straight no chaser': {'label': 0, 'tags': 'filler, affirmation', 'emotion_tags': 'negative, neutral'},
    'like no bs': {'label': 0, 'tags': 'colloquial, sarcasm, emphasis, hesitation, affirmation, filler', 'emotion_tags': 'negative, positive, supportive, neutral, confused, sarcastic'},
    'real shit': {'label': -1, 'tags': 'emphasis, sarcasm', 'emotion_tags': 'negative, confused'},
    'like keep it 100': {'label': 0, 'tags': 'affirmation, emphasis, colloquial', 'emotion_tags': 'positive, supportive'},
    'no cap fr': {'label': 0, 'tags': 'emphasis, hesitation, colloquial, sarcasm, transition, filler', 'emotion_tags': 'negative, confused, neutral, sarcastic'},
    'like straight facts': {'label': 1, 'tags': 'affirmation', 'emotion_tags': 'confidence, clarity'},
    'deadass fr': {'label': 0, 'tags': 'sarcasm, emphasis, colloquial, filler', 'emotion_tags': 'negative, sarcastic, confused'},
    'like no shade': {'label': 0, 'tags': 'emphasis, affirmation, colloquial', 'emotion_tags': 'negative, confused, neutral, positive, supportive'},
    'straight talk': {'label': 1, 'tags': 'emphasis, affirmation, colloquial', 'emotion_tags': 'neutral, positive'},
    'like no tea': {'label': 0, 'tags': 'colloquial, emphasis, sarcasm, filler, hesitation', 'emotion_tags': 'negative, confused, neutral, sarcastic'},
    'facts only': {'label': 0, 'tags': 'emphasis, affirmation', 'emotion_tags': 'clarity, assertiveness'},
    'like real shit': {'label': -1, 'tags': 'emphasis', 'emotion_tags': 'negative, confused'},
    'no cap no lie': {'label': 1, 'tags': 'affirmation, emphasis', 'emotion_tags': 'negative, positive, neutral, supportive'},
    'like keep it real': {'label': 1, 'tags': 'emphasis, colloquial, affirmation', 'emotion_tags': 'supportive, neutral'},
    'alright mate': {'label': 0, 'tags': 'affirmation, emphasis, colloquial, transition', 'emotion_tags': 'supportive, positive'},
    'you alright': {'label': 0, 'tags': 'affirmation, emphasis, transition, colloquial, hesitation', 'emotion_tags': 'supportive, positive, confused'},
    'cheers then': {'label': 1, 'tags': 'affirmation, emphasis, transition, colloquial', 'emotion_tags': 'positive, supportive'},
    'ta muchly': {'label': 0, 'tags': 'emphasis, affirmation, colloquial, sarcasm, transition', 'emotion_tags': 'positive, supportive, sarcastic, confused'},
    'oi mate': {'label': 0, 'tags': 'affirmation, emphasis, colloquial, transition, hesitation', 'emotion_tags': 'supportive, positive, confused, sarcastic'},
    'right then': {'label': 0, 'tags': 'affirmation, emphasis, transition, colloquial', 'emotion_tags': 'supportive, positive'},
    'you good mate': {'label': 1, 'tags': 'affirmation, emphasis, colloquial, transition, sarcasm', 'emotion_tags': 'supportive, positive'},
    'innit though': {'label': 0, 'tags': 'emphasis, affirmation, sarcasm, colloquial, hesitation, transition, filler', 'emotion_tags': 'positive, sarcastic, supportive, neutral, confused'},
    'like mate': {'label': 0, 'tags': 'affirmation, emphasis, colloquial', 'emotion_tags': 'supportive, positive'},
    'cheers mate': {'label': 1, 'tags': 'affirmation, emphasis, colloquial, transition', 'emotion_tags': 'supportive, positive'},
    'ta for that': {'label': 0, 'tags': 'emphasis, affirmation, colloquial, sarcasm, transition', 'emotion_tags': 'positive, supportive, sarcastic'},
    'oi you': {'label': 0, 'tags': 'affirmation, colloquial, emphasis, sarcasm, transition, hesitation', 'emotion_tags': 'confused, supportive, negative, sarcastic, positive'},
    'right mate': {'label': 0, 'tags': 'affirmation, emphasis, colloquial, transition', 'emotion_tags': 'supportive, positive'},
    'you alright then': {'label': 0, 'tags': 'affirmation, emphasis, transition, colloquial, hesitation', 'emotion_tags': 'supportive, positive, confused'},
    'innit like': {'label': 0, 'tags': 'affirmation, emphasis, colloquial, sarcasm, transition', 'emotion_tags': 'positive, supportive, neutral, sarcastic, confused'},
    'mate you know': {'label': 0, 'tags': 'affirmation, emphasis, colloquial, transition', 'emotion_tags': 'supportive, positive'},
    'cheers for that': {'label': 1, 'tags': 'affirmation, emphasis, transition', 'emotion_tags': 'positive, supportive'},
    'ta like': {'label': 0, 'tags': 'affirmation, emphasis, colloquial, transition, sarcasm', 'emotion_tags': 'positive, supportive'},
    "oi c'mon": {'label': 0, 'tags': 'affirmation, colloquial, emphasis, sarcasm, hesitation, transition', 'emotion_tags': 'confused, sarcastic, negative, supportive, positive'},
    'right you are': {'label': 0, 'tags': 'affirmation, emphasis, colloquial, transition, sarcasm', 'emotion_tags': 'supportive, positive'},
    'you good then': {'label': 1, 'tags': 'affirmation, emphasis, transition, colloquial, sarcasm', 'emotion_tags': 'positive, supportive'},
    'innit right': {'label': 0, 'tags': 'affirmation, emphasis, colloquial, transition', 'emotion_tags': 'positive, supportive'},
    'mate like': {'label': 0, 'tags': 'affirmation, emphasis, colloquial, transition', 'emotion_tags': 'supportive, positive'},
    'cheers now': {'label': 1, 'tags': 'affirmation, emphasis, transition, colloquial', 'emotion_tags': 'positive, supportive'},
    'ta then': {'label': 0, 'tags': 'affirmation, emphasis, transition, colloquial, sarcasm', 'emotion_tags': 'positive, supportive, sarcastic'},
    'oi right': {'label': 0, 'tags': 'affirmation, emphasis, colloquial, transition, sarcasm, hesitation', 'emotion_tags': 'positive, supportive, confused, sarcastic'},
    'you alright mate': {'label': 0, 'tags': 'affirmation, emphasis, colloquial, transition, hesitation', 'emotion_tags': 'supportive, confused, positive'},
    'in sooth': {'label': 0, 'tags': 'colloquial, emphasis, affirmation, transition', 'emotion_tags': 'supportive, positive, neutral'},
    'to wit': {'label': 0, 'tags': 'emphasis, colloquial, affirmation, sarcasm, transition', 'emotion_tags': 'positive, sarcastic, supportive, confused'},
    'in truth': {'label': 0, 'tags': 'affirmation, emphasis', 'emotion_tags': 'positive, supportive'},
    'peradventure': {'label': 0, 'tags': 'emphasis, affirmation', 'emotion_tags': 'positive, supportive'},
    'in sooth verily': {'label': 0, 'tags': 'affirmation, emphasis, colloquial, transition', 'emotion_tags': 'positive, supportive, neutral'},
    'prithee now': {'label': 0, 'tags': 'emphasis, affirmation, colloquial, transition, hesitation, sarcasm', 'emotion_tags': 'positive, supportive, sarcastic, confused'},
    'forsooth then': {'label': 0, 'tags': 'affirmation, colloquial, emphasis, transition, filler', 'emotion_tags': 'supportive, neutral, positive'},
    'verily so': {'label': 0, 'tags': 'affirmation, emphasis, transition, colloquial', 'emotion_tags': 'positive, supportive'},
    'methinks perhaps': {'label': 0, 'tags': 'hesitation, colloquial, emphasis, sarcasm', 'emotion_tags': 'confused'},
    'perchance maybe': {'label': 0, 'tags': 'emphasis, hesitation, colloquial, transition', 'emotion_tags': 'confused'},
    'mayhap so': {'label': 0, 'tags': 'emphasis, affirmation, transition, hesitation, colloquial', 'emotion_tags': 'supportive, positive, confused'},
    'in truth now': {'label': 0, 'tags': 'affirmation, emphasis', 'emotion_tags': 'positive, supportive'},
    'to wit then': {'label': 0, 'tags': 'emphasis, colloquial, affirmation, transition, sarcasm', 'emotion_tags': 'sarcastic, positive, supportive'},
    'haply so': {'label': 0, 'tags': 'emphasis, affirmation, colloquial, hesitation, transition, sarcasm', 'emotion_tags': 'positive, supportive, confused, negative'},
    'belike maybe': {'label': 0, 'tags': 'hesitation, colloquial, emphasis, affirmation, transition', 'emotion_tags': 'supportive, confused, positive'},
    'forasmuche as': {'label': 0, 'tags': 'emphasis, affirmation, sarcasm, hesitation, colloquial, transition', 'emotion_tags': 'positive, supportive, sarcastic, confused, negative'},
    'withal then': {'label': 0, 'tags': 'affirmation, emphasis, transition, filler, colloquial', 'emotion_tags': 'supportive, neutral, positive, confused'},
    'in sooth like': {'label': 0, 'tags': 'affirmation, colloquial, emphasis', 'emotion_tags': 'supportive, positive, neutral'},
    'peradventure now': {'label': 0, 'tags': 'emphasis, affirmation', 'emotion_tags': 'positive, supportive'},
    'like omg': {'label': 0, 'tags': 'emphasis, affirmation, sarcasm, colloquial, transition', 'emotion_tags': 'confused, sarcastic'},
    'for real tho': {'label': 0, 'tags': 'affirmation, emphasis', 'emotion_tags': 'positive, supportive'},
    'no cap tho': {'label': 0, 'tags': 'hesitation, emphasis, colloquial, sarcasm, filler, transition', 'emotion_tags': 'negative, confused, neutral'},
    'like lmao': {'label': 1, 'tags': 'sarcasm, colloquial, emphasis, affirmation, transition', 'emotion_tags': 'sarcastic, confused, supportive'},
    'straight up tho': {'label': 1, 'tags': 'emphasis, affirmation', 'emotion_tags': 'positive'},
    'bet af': {'label': 0, 'tags': 'affirmation, emphasis, sarcasm, colloquial, hesitation, transition', 'emotion_tags': 'supportive, positive, confused, sarcastic'},
    'like tbh': {'label': 0, 'tags': 'affirmation, colloquial, emphasis, sarcasm, transition, hesitation', 'emotion_tags': 'positive, supportive, sarcastic, neutral'},
    'imo like': {'label': 0, 'tags': 'emphasis, affirmation, colloquial, transition', 'emotion_tags': 'supportive, positive, confused'},
    'fyi tho': {'label': 0, 'tags': 'hesitation, affirmation, colloquial, sarcasm, emphasis, filler, transition', 'emotion_tags': 'confused, negative, sarcastic, neutral, supportive'},
    'brb like': {'label': 0, 'tags': 'affirmation, colloquial, emphasis, sarcasm, transition', 'emotion_tags': 'positive, supportive, sarcastic, confused'},
    'btw tho': {'label': 0, 'tags': 'emphasis, sarcasm, colloquial, transition, affirmation, hesitation', 'emotion_tags': 'confused, sarcastic, supportive'},
    'irl like': {'label': 0, 'tags': 'emphasis, colloquial, affirmation, sarcasm, transition, hesitation', 'emotion_tags': 'supportive, positive, confused, sarcastic'},
    'smh tho': {'label': 0, 'tags': 'sarcasm, emphasis, colloquial, hesitation, transition', 'emotion_tags': 'sarcastic, confused, negative'},
    'lmao like': {'label': 1, 'tags': 'sarcasm, emphasis, affirmation, colloquial, transition', 'emotion_tags': 'supportive, positive, sarcastic, confused'},
    'rofl tho': {'label': 1, 'tags': 'sarcasm, emphasis, colloquial, transition, hesitation', 'emotion_tags': 'sarcastic, negative, confused'},
    'af like': {'label': 0, 'tags': 'affirmation, emphasis, colloquial, transition', 'emotion_tags': 'supportive, positive, confused'},
    'lit tho': {'label': 0, 'tags': 'emphasis, sarcasm, affirmation, transition, colloquial', 'emotion_tags': 'positive, supportive, sarcastic'},
    'yolo like': {'label': 1, 'tags': 'affirmation, colloquial, emphasis, transition, sarcasm', 'emotion_tags': 'supportive, positive, confused, sarcastic'},
    'savage tho': {'label': -1, 'tags': 'sarcasm, emphasis', 'emotion_tags': 'negative, sarcastic, confused'},
    'on fleek tho': {'label': 0, 'tags': 'emphasis, affirmation, colloquial, transition, sarcasm', 'emotion_tags': 'positive, supportive'},
    "poppin' like": {'label': 0, 'tags': 'emphasis, colloquial, affirmation, transition, sarcasm', 'emotion_tags': 'positive, supportive, confused, sarcastic'},
    'turnt tho': {'label': 0, 'tags': 'emphasis, colloquial, sarcasm, transition', 'emotion_tags': 'negative, sarcastic, confused'},
}