intensifier_words = {
    # 高強度增強詞 (1.8-2.5)
    "extremely": 2.0,
    "absolutely": 2.1,
    "incredibly": 2.0,
    "completely": 1.9,
    "amazingly": 1.9,
    "astonishingly": 2.1,
    "colossally": 2.2,
    "decidedly": 1.8,
    "dramatically": 1.9,
    "emphatically": 1.8,
    "enormously": 2.1,
    "entirely": 1.9,
    "especially": 1.8,
    "exceptionally": 2.0,
    "exceedingly": 1.9,
    "excessively": 1.9,
    "fantastically": 2.0,
    "fully": 1.8,
    "greatly": 1.8,
    "highly": 1.8,
    "immensely": 2.1,
    "intensely": 2.0,
    "majorly": 1.8,
    "massively": 2.1,
    "mightily": 1.9,
    "outstandingly": 2.0,
    "overwhelmingly": 2.2,
    "particularly": 1.8,
    "phenomenally": 2.1,
    "profoundly": 2.0,
    "radically": 1.9,
    "remarkably": 1.9,
    "seriously": 1.8,
    "severely": 1.9,
    "significantly": 1.8,
    "specially": 1.8,
    "strikingly": 1.9,
    "substantially": 1.8,
    "thoroughly": 1.8,
    "totally": 1.9,
    "tremendously": 2.1,
    "truly": 1.8,
    "utterly": 2.0,
    "violently": 2.1,
    "wonderfully": 1.8,
    "abominably": 2.2,
    "astoundingly": 2.1,
    "blazingly": 2.2,
    "brilliantly": 2.0,
    "desperately": 2.0,
    "divinely": 2.1,
    "epically": 2.2,
    "exorbitantly": 2.2,
    "extraordinarily": 2.2,
    "fabulously": 2.0,
    "ferociously": 2.1,
    "fiercely": 2.0,
    "formidably": 2.0,
    "gloriously": 2.0,
    "hugely": 2.0,
    "immeasurably": 2.2,
    "infinitely": 2.5,
    "monumentally": 2.2,
    "outrageously": 2.1,
    "overly": 1.9,
    "prodigiously": 2.2,
    "shockingly": 2.0,
    "spectacularly": 2.1,
    "staggeringly": 2.2,
    "stunningly": 2.1,
    "superbly": 2.0,
    "supremely": 2.2,
    "surpassingly": 2.1,
    "unbelievably": 2.2,
    "unimaginably": 2.3,
    "vastly": 2.0,
    "vehemently": 2.1,
    "vigorously": 1.9,
    "wildly": 2.0,
    "astronomically": 2.3,
    "blatantly": 1.9,
    "copiously": 2.0,
    "dazzlingly": 2.1,
    "devastatingly": 2.2,
    "explosively": 2.1,
    "flamboyantly": 2.0,
    "grandiosely": 2.1,
    "heroically": 2.0,
    "lavishly": 2.0,
    "marvellously": 2.0,
    "miraculously": 2.1,
    "monstrously": 2.2,
    "palpably": 1.8,
    "resoundingly": 2.0,
    "splendidly": 2.0,
    "stupendously": 2.2,
    "transcendently": 2.3,
    "unbearably": 2.2,
    "unthinkably": 2.3,
    "insanely": 2.2,
    "ridiculously": 2.0,
    "bloody": 1.9,
    "crazy": 1.9,
    "devilishly": 2.0,
    "dreadfully": 1.9,
    "frightfully": 1.9,
    "hella": 2.1,
    "mad": 1.9,
    "mega": 2.1,
    "super": 1.9,
    "terribly": 1.9,
    "uber": 2.0,
    "ultra": 2.1,
    "wicked": 2.0,
    
    # 中高強度增強詞 (1.4-1.8)
    "very": 1.5,
    "so": 1.6,
    "too": 1.5,
    "really": 1.6,
    "definitely": 1.7,
    "mighty": 1.7,
    "proper": 1.5,
    "dead": 1.6,
    "certainly": 1.6,
    "clearly": 1.5,
    "indeed": 1.5,
    "literally": 1.7,
    "obviously": 1.6,
    "plainly": 1.5,
    "positively": 1.6,
    "precisely": 1.5,
    "simply": 1.4,
    "surely": 1.5,
    "undoubtedly": 1.7,
    "unquestionably": 1.7,
    
    # 中等強度增強詞 (1.0-1.4)
    "acceptably": 1.1,
    "amply": 1.3,
    "comfortably": 1.2,
    "decently": 1.1,
    "discernibly": 1.0,
    "evidently": 1.3,
    "generously": 1.3,
    "measurably": 1.0,
    "passably": 1.0,
    "perceptibly": 1.0,
    "plausibly": 1.1,
    "prominently": 1.3,
    "respectably": 1.2,
    "satisfactorily": 1.1,
    "sizably": 1.3,
    "substantively": 1.3,
    "tangibly": 1.2,
    "visibly": 1.2,
    "well": 1.2,
    "workably": 1.0,
    "abundantly": 1.4,
    "credibly": 1.2,
    "demonstrably": 1.3,
    "effectively": 1.3,
    "materially": 1.2,
    "palpably": 1.2,
    "practically": 1.1,
    "sensibly": 1.1,
    "solidly": 1.3,
    "suitably": 1.1,
    "apparently": 1.0,
    "detectably": 1.0,
    "manifestly": 1.3,
    "markedly": 1.3,
    "observably": 1.1,
    "readily": 1.2,
    "relevantly": 1.1,
    "saliently": 1.2,
    "soundly": 1.2,
    "stably": 1.1,
    
    # 低強度增強詞 (0.3-0.9)
    "a smidge": 0.4,
    "a tad": 0.5,
    "almost": 0.8,
    "gently": 0.7,
    "just about": 0.8,
    "nearly": 0.8,
    "nominally": 0.6,
    "some": 0.6,
    "sparingly": 0.5,
    "subtly": 0.5,
    "to a degree": 0.7,
    "to some extent": 0.7,
    "barely": 0.4,
    "cursorily": 0.5,
    "feebly": 0.4,
    "lightly": 0.6,
    "modestly": 0.7,
    "somewhat": 0.7,
    "superficially": 0.5,
    "tentatively": 0.5,
    "weakly": 0.4,
    "a touch": 0.5,
    "a trifle": 0.4,
    "hardly": 0.4,
    "in part": 0.6,
    "in some measure": 0.6,
    "scantly": 0.4,
    "shyly": 0.5,
    "slenderly": 0.4,
    "sparsely": 0.4,
    "to a certain degree": 0.6,
    "to a certain extent": 0.6,
    "to a point": 0.6,
    "to an extent": 0.6,
    "adequately": 1.1,
    "appreciably": 1.2,
    "considerably": 1.3,
    "distinctly": 1.2,
    "fairly": 1.1,
    "moderately": 1.1,
    "notably": 1.3,
    "noticeably": 1.2,
    "pretty": 1.2,
    "quite": 1.3,
    "rather": 1.2,
    "reasonably": 1.1,
    "relatively": 1.0,
    "sufficiently": 1.1,
    "tolerably": 1.0,
    "unusually": 1.3,
    "actually": 1.0,
    
    # 減弱強度詞 (0.3-0.9)
    "slightly": 0.7,
    "somewhat": 0.8,
    "barely": 0.4,
    "hardly": 0.4,
    "just": 0.8,
    "a bit": 0.7,
    "a little": 0.6,
    "faintly": 0.5,
    "kind of": 0.7,
    "kinda": 0.7,
    "marginally": 0.6,
    "mildly": 0.7,
    "minimally": 0.4,
    "partially": 0.6,
    "partly": 0.6,
    "scarcely": 0.3,
    "sort of": 0.7,
    "vaguely": 0.5,
    # 強調語 (1.5-1.8)
    "assuredly": 1.6,
    "categorically": 1.7,
    "conclusively": 1.7,
    "confidently": 1.6,
    "decisively": 1.7,
    "demonstratively": 1.6,
    "directly": 1.5,
    "expressly": 1.6,
    "flatly": 1.5,
    "genuinely": 1.5,
    "honestly": 1.5,
    "irrefutably": 1.8,
    "patently": 1.6,
    "pointedly": 1.5,
    "straightforwardly": 1.5,
    "truly": 1.6,
    "unarguably": 1.7,
    "undeniably": 1.7,
    "unequivocally": 1.7,
    "verifiably": 1.6,
    "avowedly": 1.5,
    "certifiably": 1.6,
    "explicitly": 1.6,
    "indisputably": 1.7,
    "inherently": 1.5,
    "intrinsically": 1.5,
    "markedly": 1.5,
    "openly": 1.5,
    "overtly": 1.5,
    "transparently": 1.5,
    "admittedly": 1.5,
    "authentically": 1.5,
    "boldly": 1.5,
    "candidly": 1.5,
    "frankly": 1.5,
    "incontestably": 1.7,
    "indubitably": 1.7,
    "tangibly": 1.5,
    "verily": 1.6,
    "visibly": 1.5,
    
    # 俚語/口語 (1.7-2.3)
    "damn": 1.8,
    "friggin'": 1.9,
    "frickin'": 1.9,
    "hecka": 2.0,
    "way": 1.8,
    "totally": 1.9,
    "absurdly": 2.0,
    "batshit": 2.2,
    "bonkers": 2.0,
    "bunch": 1.7,
    "effing": 2.0,
    "freaking": 1.9,
    "goddamn": 2.1,
    "heaps": 1.8,
    "loads": 1.8,
    "nuts": 1.9,
    "shitloads": 2.2,
    "ton": 1.9,
    "tons": 2.0,
    "whopping": 2.0,
    "zillion": 2.3,
    "cray": 1.9,
    "dope": 1.8,
    "extra": 1.7,
    "madly": 1.9,
    "sick": 1.8,
    "stupid": 1.9,
    "wild": 1.8,
    "yuge": 2.0,
    "bigly": 1.9,
    "helluva": 2.0,
    "humongous": 2.1,
    "jumbo": 1.9,
    "kooky": 1.7,
    "ludicrously": 2.1,
    "nutter": 1.8,
    "off-the-charts": 2.2,
    "outta": 1.8,
    "psycho": 2.0,
    "screamingly": 2.1,
    "shitton": 2.2,
    "straight-up": 1.9,
    "super-duper": 2.1,
    "way too": 2.0,
    "whacko": 1.9,
    "zanily": 1.8,
    "bleedin'": 1.9,
    "chuffing": 1.8,
    "flippin'": 1.8,
    "sodding": 1.8,
    
    # 文學/詩歌用詞 (1.7-2.2)
    "beauteously": 1.8,
    "bountifully": 1.9,
    "celestially": 2.1,
    "divinely": 2.1,
    "exaltedly": 2.0,
    "exquisitely": 2.0,
    "felicitously": 1.8,
    "graciously": 1.7,
    "harmoniously": 1.8,
    "luminously": 1.9,
    "majestically": 2.0,
    "nobly": 1.7,
    "opulently": 1.9,
    "radiantly": 1.9,
    "rapturously": 2.1,
    "resplendently": 2.0,
    "serenely": 1.7,
    "sublimely": 2.0,
    "sumptuously": 1.9,
    "wondrously": 2.0,
    "angelically": 2.0,
    "blissfully": 1.9,
    "charmingly": 1.7,
    "delightfully": 1.8,
    "enchantingly": 1.9,
    "ethereally": 2.0,
    "gloriously": 2.0,
    "heavenly": 2.0,
    "idyllically": 1.9,
    "lyrically": 1.8,
    "picturesquely": 1.8,
    "poetically": 1.8,
    "ravishingly": 2.0,
    "splendorously": 2.1,
    "vividly": 1.8,
    # 地區性/非正式變體 (1.6-2.1)
    "jolly": 1.6,
    "bleeding": 1.9,
    "blooming": 1.7,
    "blinking": 1.7,
    "bally": 1.7,
    "dashed": 1.6,
    "deucedly": 1.8,
    "doggone": 1.8,
    "goshdarn": 1.8,
    "plumb": 1.7,
    "darn": 1.7,
    "gol-darn": 1.8,
    "gosh": 1.6,
    "ruddy": 1.7,
    "stinking": 1.9,
    "whacking": 1.9,
    "blasted": 1.9,
    "confounded": 1.8,
    "cursed": 1.9,
    "damnably": 2.0,
    "deuced": 1.8,
    "effin'": 2.0,
    "frigging": 2.0,
    "goddam": 2.1,
    "goddamn": 2.1,
    "hellish": 1.9,
    "pesky": 1.6,
    "shitting": 2.1,
    "friggin": 2.0,
    "bleedin": 1.9,
    "chuffin": 1.8,
    "soddin": 1.9,
    "bloomin": 1.7,
    "dashin": 1.6,
    
    # 其他增強詞 (1.5-2.2)
    "abjectly": 1.9,
    "acutely": 1.8,
    "aggressively": 1.9,
    "alarmingly": 1.9,
    "ardently": 1.8,
    "avidly": 1.7,
    "brazenly": 1.8,
    "brutally": 2.0,
    "burningly": 1.9,
    "compellingly": 1.8,
    "convincingly": 1.7,
    "crucially": 1.8,
    "direly": 1.9,
    "distressingly": 1.9,
    "dominantly": 1.8,
    "eagerly": 1.6,
    "energetically": 1.7,
    "fervently": 1.8,
    "forcefully": 1.9,
    "frantically": 1.9,
    "furiously": 2.0,
    "grievously": 1.9,
    "harshly": 1.8,
    "heavily": 1.8,
    "hotly": 1.7,
    "keenly": 1.7,
    "painfully": 1.9,
    "piercingly": 1.9,
    "poignantly": 1.8,
    "potently": 1.8,
    "powerfully": 1.9,
    "pressingly": 1.7,
    "sharply": 1.8,
    "shrilly": 1.7,
    "sorely": 1.8,
    "stormily": 1.9,
    "strenuously": 1.8,
    "tempestuously": 2.0,
    "tensely": 1.7,
    "throbbingly": 1.8,
    "tormentingly": 2.0,
    "torturously": 2.0,
    "tragically": 1.9,
    "turbulently": 1.9,
    "urgently": 1.8,
    "venomously": 2.0,
    "viciously": 2.0,
    "vitally": 1.7,
    "vociferously": 1.9,
    "weightily": 1.7,
    "zealously": 1.8,
    
    # 現代/網路用語 (1.7-2.3)
    "big-time": 2.0,
    "epicly": 2.2,
    "ginormous": 2.2,
    "mega-ly": 2.2,
    "off-the-hook": 2.1,
    "over-the-top": 2.2,
    "real": 1.7,
    "so damn": 2.1,
    "so freaking": 2.1,
    "so hella": 2.2,
    "straight": 1.7,
    "too damn": 2.1,
    "way cool": 1.9,
    "way out": 1.9,
    "wickedly": 2.0,
    "amped": 1.9,
    "badass": 2.0,
    "beastly": 2.0,
    "bitchin'": 2.0,
    "bona fide": 1.7,
    "crunk": 2.0,
    "fire": 2.1,
    "hype": 2.0,
    "insane": 2.1,
    "lit": 2.0,
    "next-level": 2.2,
    "on fleek": 2.0,
    "poppin'": 1.9,
    "savage": 2.1,
    "slayin'": 2.1,
    "tight": 1.8,
    "turnt": 2.0,
    "unreal": 2.1,
    
    # 細微變體 (0.4-1.5)
    "a smidgen": 0.4,
    "a wee bit": 0.5,
    "ever so": 0.7,
    "fairly well": 1.1,
    "in a big way": 1.5,
    "kinda sorta": 0.6,
    "more or less": 0.7,
    "pretty much": 1.0,
    "somewhat more": 0.8,
    "sorta kinda": 0.6,
    "to a fault": 1.4,
    "to a great degree": 1.5,
    "to a large extent": 1.4,
    "to some degree": 0.8
}