negation_words = {
    # Original set
    "not", "no", "never", "n't", "cannot",
    "ain't", "aren't", "can't", "couldn't", "didn't", "doesn't",
    "don't", "hasn't", "haven't", "hadn't", "isn't", "mustn't",
    "needn't", "shouldn't", "wasn't", "weren't", "won't", "wouldn't",
    "shan't", "daren't", "mayn't", "mightn't", "oughtn't",
    "by no means", "hardly", "in no way", "neither", "nobody",
    "none", "nor", "nothing", "nowhere", "impossible",
    "on no account", "scarcely", "barely", "seldom", "rarely",
    "at no time", "under no circumstances", "not at all",
    "not in the least", "not a bit", "no way", "no longer",
    "no more", "not anymore", "no chance", "null", "void",
    "nix", "zilch", "nil", "nada", "zero", "none whatsoever",
    "non", "un", "dis", "in", "im", "il", "ir", "a", "anti", "counter",
    "de", "mis", "mal", "pseudo", "quasi",
    "few", "little", "less", "least", "insufficient", "inadequate",
    "scarce", "limited", "minimal", "negligible", "slight",
    "sparse", "thin", "meager", "deficient", "paltry",
    "deny", "fail", "reject", "refuse", "avoid", "prevent", "prohibit",
    "forbid", "exclude", "without", "lacking", "lack of", "absence",
    "absent", "missing", "omit", "omission", "avert", "block", "cease",
    "decline", "deflect", "disallow", "discard", "dismiss", "eliminate",
    "elude", "evade", "halt", "hinder", "ignore", "impede", "obstruct",
    "preclude", "repel", "repudiate", "resist", "shun", "stop", "thwart",
    "undermine", "terminate", "withhold", "veto", "renounce", "disavow",
    "discontinue", "disregard", "abolish", "cancel", "annul", "rescind",
    "revoke", "invalidate", "nullify", "repeal", "retract", "waive",
    "against", "oppose", "contrary", "contradict", "negate", "refute",
    "rebut", "dispute", "object to", "instead of", "rather than",
    "versus", "contrary to", "unlike", "nevertheless", "nonetheless",
    "however", "although", "though", "but", "yet", "despite", "in spite of",
    "regardless", "even though", "conversely", "on the contrary",
    "otherwise", "antithetical", "opposing", "opposite", "reverse",
    "unless", "except", "but for", "if not", "only if", "lest",
    "aside from", "apart from", "barring", "excluding", "save for",
    "other than", "with the exception of", "excepting", "outside of",
    "anything but", "far from", "last but not least", "least of all",
    "little or no", "next to nothing", "not for the world", "not in a million years",
    "once in a blue moon", "out of the question", "to say nothing of",
    "wanting", "notwithstanding",
    "nope", "nah", "naw", "nowt", "nought", "not ever", "not once",
    "not really", "not quite", "not yet", "nohow", "nonexistent",
    "unavailable", "unexisting", "nonpresent", "gone", "missing out",
    "ain't gonna", "cain't", "don'cha", "dunno", "hadn't've", "hasn't've",
    "won't've", "wouldn't've", "shouldn't've", "mightn't've", "can't've",
    "wudn't", "willnae", "didnae", "dinnae", "wasnae", "havenae",
    "isnae", "couldnae", "wouldnae", "shudn't", "mustn't've",
    "ab", "an", "de-", "dis-", "in-", "non-", "un-", "anti-", "counter-",
    "contra", "ob", "sub", "under", "over", "out", "off", "ex",
    "extra", "hyper", "infra", "inter", "intra", "macro", "micro",
    "multi", "omni", "per", "post", "pre", "pro", "retro", "super",
    "trans", "ultra", "vice", "with", "without-", "neo", "over-",
    "scant", "bare", "trifling", "trivial", "inconsequential", "insignificant",
    "petty", "minor", "piddling", "inappreciable", "inconsiderable", "tiny",
    "small", "slender", "skimpy", "short", "low", "dearth", "paucity",
    "scarcity", "shortage", "want", "deficit", "deprived", "destitute",
    "lacking in", "bereft", "void of", "empty", "vacant", "barren",
    "desolate", "devoid", "exiguous", "frugal", "lean", "stingy",
    "in short supply", "next to none", "almost none", "bare minimum",
    "abandon", "abate", "abdicate", "abrogate", "averted", "ban", "bar",
    "blackball", "bypass", "circumvent", "counteract", "curtail", "debar",
    "deter", "dismantle", "dispel", "divert", "drop", "eschew", "expel",
    "forestall", "forsake", "frustrate", "inhibit", "intercept", "neglect",
    "nix on", "overrule", "proscribe", "quash", "relinquish", "shirk",
    "sidestep", "suppress", "turn down", "vitiate", "ward off", "withdraw",
    "abnegate", "abstain", "defeat", "demolish", "deplete", "deprive",
    "derail", "destroy", "dismay", "forswear", "neutralize", "offset",
    "overthrow", "parry", "restrain", "sabotage", "scuttle", "stifle",
    "subvert", "torpedo", "undo", "unmake", "upend", "vacate",
    "in lieu of", "as opposed to", "in contrast to", "counter to", "at odds with",
    "over against", "in opposition to", "not like", "distinct from", "different from",
    "divergent", "incompatible", "adverse", "hostile", "antagonistic",
    "conflicting", "clashing", "contradictory", "inconsistent", "repugnant",
    "irreconcilable", "discordant", "dissonant", "at variance", "opposed",
    "inverted", "antipodal", "polar", "antonymic", "contrariwise",
    "in reverse", "backwards", "vice versa", "on the other hand", "by contrast",
    "save", "but in", "short of", "failing", "without exception", "bar",
    "beyond", "outside", "absent from", "free from", "in the absence of",
    "not counting", "leaving out", "omitting", "barring the", "except for the",
    "in default of", "lacking for", "sans", "wanting in", "devoid of",
    "bereft of", "empty of", "voided of", "stripped of", "cleared of",
    "no dice", "fat chance", "not likely", "no go", "nary", "never ever",
    "not by a long shot", "not in the slightest", "not hardly", "nope nope",
    "nah uh", "not on your life", "not a chance", "never in a million years",
    "not in a thousand years", "not for love nor money", "no can do",
    "not by any means", "not even close", "no sir", "no ma'am", "nada chance",
    "zero chance", "not one iota", "not a shred", "not a smidge",
    "not a trace", "not a speck", "not a whit", "not a jot", "not a tittle",
    "not the least bit", "no such thing", "nonstarter", "dead end",
    "off the table", "out of bounds", "not permissible", "verboten",
    "taboo", "banned", "prohibited", "disallowed", "forbidden", "outlawed",
    "nary a", "scantily", "sparingly", "infrequently", "occasionally",
    "seldomly", "uncommonly", "unfrequently", "not often", "almost never",
    "hardly ever", "rarely ever", "seldom if ever", "in no case",
    "under no condition", "on no condition", "at no point", "in no event",
    "by no stretch", "not under any circumstances", "never once",
    "not in any way", "not to mention", "let alone", "much less",
    "still less", "far less", "even less", "never mind", "not to speak of",
    "nope", "nah", "naw", "zip", "zippo", "bupkis", "diddly", "squat",
    "doodly-squat", "jack", "bugger all", "sod all", "damn all", "f-all",
    "sweet fa", "nothing doing", "no deal", "no bueno", "no soap",
    "not happening", "no joy", "no luck", "no shot", "no dice whatsoever",
    "zilch all", "nada nada", "nil nil", "zero zero", "nowt at all",
    "sweet nothing", "big fat zero", "not a damn thing", "not a bloody thing",
    "not a blasted thing", "not a cursed thing", "not a darn thing",
    "not a single thing", "not one bit", "not one darn bit", "not a lick",
    "not a scrap", "not an ounce", "not a drop", "not a crumb",

    # 新增基本否定詞和縮寫
    "ne'er", "ain't never", "shan't've", "don't've", "aren't've",
    "is'n't", "was'n't", "weren't've", "haven't've", "hadn't'a",
    "can't'a", "won't'a", "wouldn't'a", "shouldn't'a", "mightn't'a",
    "ain't'a", "n't'a", "nope-a-dope", "nah-uh", "naw-naw",
    "not a one", "not a soul", "not any", "no one", "not anybody",
    "not anyone", "not anything", "not anywhere", "never again",
    "not now", "not here", "not there", "not nowhere", "non-available",
    "unattainable", "unreachable", "unobtainable", "inaccessible",
    "not present", "not around", "not existent", "not to be found",

    # 新增否定前綴
    "un-", "dis-", "in-", "non-", "anti-", "counter-", "de-", "mis-",
    "mal-", "a-", "ab-", "an-", "ob-", "sub-", "over-", "under-",
    "extra-", "hyper-", "infra-", "inter-", "intra-", "macro-", "micro-",
    "multi-", "omni-", "per-", "post-", "pre-", "pro-", "retro-",
    "super-", "trans-", "ultra-", "vice-", "neo-", "ambi", "amphi",
    "circum", "cis", "co", "com", "con", "dia", "dif", "dys", "en",
    "epi", "fore", "hemi", "meta", "para", "peri", "syn", "tri",

    # 新增量詞否定
    "pittance", "modicum", "iota", "smidgen", "smidge", "tad", "dash",
    "bit", "speck", "morsel", "scrap", "crumb", "dab", "jot", "tittle",
    "whit", "atom", "grain", "mite", "scintilla", "shred", "trifle",
    "drop", "drib", "driblet", "ounce", "pinch", "sprinkle", "tinge",
    "trace", "vestige", "shadow", "scarcely any", "hardly any",
    "next to no", "barely any", "almost no", "nigh on none", "scant of",
    "short of", "devoid in", "absent in", "deficient in", "low on",
    "meager in", "sparse in", "thin on", "wanting of", "lacking of",

    # 新增隱含否定
    "spurn", "rebuff", "snub", "disdain", "scorn", "ostracize",
    "blacklist", "boycott", "embargo", "sanction", "depose", "dethrone",
    "evict", "oust", "eject", "expunge", "erase", "obliterate", "annihilate",
    "extinguish", "quell", "squelch", "smother", "stave off", "fend off",
    "keep at bay", "hold back", "push back", "brush off", "shrug off",
    "turn away", "turn back", "ward away", "keep off", "drive off",
    "beat back", "chase away", "send packing", "shut out", "lock out",
    "rule out", "count out", "cut out", "leave out", "pass over",
    "skip over", "gloss over", "brush aside", "set aside", "cast aside",

    # 新增反對/對比詞
    "in contradistinction to", "antipode", "diametric", "diametrical",
    "polar opposite", "in direct opposition", "in stark contrast",
    "in sharp contrast", "in complete contrast", "wholly unlike",
    "utterly different", "totally opposed", "radically different",
    "fundamentally opposed", "diametrically opposed", "at cross purposes",
    "in conflict with", "inconsistent with", "repugnant to", "contradictory to",
    "irreconcilable with", "incompatible with", "adverse to", "hostile to",
    "antagonistic to", "opposed to", "contrary to the", "unlike the",
    "distinctly different", "markedly different", "vastly different",

    # 新增條件否定
    "barring from", "except as", "save as", "but as", "outside the",
    "beyond the", "apart from the", "aside from the", "excluding the",
    "omitting the", "not including", "not involving", "not encompassing",
    "not embracing", "not covering", "not containing", "free of",
    "clear of", "rid of", "purged of", "cleansed of", "stripped from",
    "divested of", "relieved of", "unburdened of", "disencumbered of",

    # 新增進階/非正式否定
    "not a snowball's chance", "not a hope in hell", "nothing of the sort",
    "no such luck", "no such deal", "not a prayer", "not in your dreams",
    "not in this lifetime", "no way Jose", "not a cat in hell's chance",
    "not a ghost of a chance", "not a shot in hell", "no bloody way",
    "no freaking way", "no damn way", "no effing way", "no sodding way",
    "no bleedin' way", "not a blasted chance", "not a cursed chance",
    "not a darn hope", "not a single hope", "not a solitary chance",
    "zilcho", "nada zip", "nil zilch", "zero nada", "nowt nada",
    "bupkis nada", "diddly zip", "squat zilch", "jack nada",
    "bugger nothing", "sod nothing", "damn nothing", "f-all nothing",

    # 新增文學/正式否定
    "forsooth not", "devoid entirely", "utterly devoid", "wholly absent",
    "completely lacking", "entirely without", "totally bereft",
    "absolutely wanting", "starkly empty", "vacuous", "nullified",
    "annulled", "abrogated", "repealed wholly", "revoked entirely",
    "invalidated fully", "rescinded totally", "retracted completely",
    "waived utterly", "forsaken entirely", "abjured", "disclaimed",
    "recanted", "abnegated wholly", "renounced fully", "eschewed entirely",
    "spurned utterly", "repudiated wholly", "disavowed completely",
    "never the less", "not the more", "not in the smallest degree",
    "not in the faintest", "not in the remotest", "not by any stretch",

    # 新增俚語/口語否定
    "nope-a-roo", "nah nah", "naw way", "zip nada", "zilcho zip",
    "bupkis squat", "diddly nada", "squat zip", "jack zilch",
    "bugger naught", "sod naught", "damn naught", "f-all zip",
    "sweet bugger all", "naff all", "nowt zip", "zero squat",
    "nada bupkis", "nil squat", "nope zilch", "nah bupkis",
    "naw zilcho", "not a zot", "not a zip", "not a nada",
    "not a bupkis", "not a diddly", "not a squat", "not a jack",
    "not a bugger", "not a sod", "not a damn", "not a f-all",
    "not a sweet fa", "no bloody chance", "no blasted hope",
    "no cursed luck", "no darn shot", "no single scrap",
    "no solitary speck", "no lone crumb", "no only jot",
    "no mere tittle", "no scant whit", "no tiny trace",
}